"""Build the transitional English display catalog with an offline CTranslate2 model.

The runtime never includes the model. It loads only the generated JSON. This
script does not edit gameplay sources and resumes from a cache under build/.
"""
from hashlib import sha256
from pathlib import Path
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
DEPS = BUILD / "translation-lite"
MODEL = BUILD / "argos-model/translate-zh_en-1_9"
CACHE = BUILD / "english-translation-cache-v4.json"
OUTPUT = ROOT / "assets/localization/legacy-en_US.json"
sys.path.insert(0, str(DEPS))

try:
    import ctranslate2
    import sentencepiece as spm
except ImportError:
    ctranslate2 = None
    spm = None

CJK = re.compile(r"[\u3400-\u9fff]")
FORMAT = re.compile(r"%(?:[-+ 0#]*)(?:\d+|\*)?(?:\.(?:\d+|\*))?[diouxXfFeEgGaAcsp]")
NAMED = re.compile(r"(?<!\{)\{(?:[A-Za-z_][A-Za-z0-9_.]*|\d+)\}(?!\})")
TAG = re.compile(r"\[(?:/?[A-Za-z][^\]\n]*|[^\]\n]*=[^\]\n]*)\]")
_SUFFIXES = "alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau upsilon phi chi psi omega".split()
WORDS = ["Placeholder" + suffix for suffix in _SUFFIXES]
WORDS += ["Placeholder" + first + second for first in _SUFFIXES for second in _SUFFIXES]

# Longest first. Protect only terms whose meaning must remain stable. Protecting
# ordinary nouns and verbs breaks Chinese sentence structure for small models.
GLOSSARY = {
    "施法预备": "Spell Preparation", "脱缚练习": "Escape Practice",
    "紧缚尖塔": "Bound Spire", "魔法少女": "Magical Girl", "魔瓶魔力": "Flask Mana",
    "临时魔力": "Temporary Mana", "施法成功率": "Cast Success Rate", "魔法伤害": "Spell Damage",
    "挣扎伤害": "Struggle Damage", "滑脱伤害": "Slip Damage", "固定伤害": "Fixed Damage",
    "抽牌堆": "Draw Pile", "弃牌堆": "Discard Pile", "消耗区": "Exhaust Pile",
    "火球术": "Fireball", "术式解锁": "Spell Unlock", "魔术手": "Mage Hand",
    "拘束之拥": "Restraint's Embrace", "身轻如燕": "Featherlight",
    "般若汤": "Hannya Brew", "淫纹": "Lewd Mark", "正义飞踢": "Justice Kick",
    "软化扣环": "Softened Buckle", "贞操锁": "Chastity Lock", "平板锁": "Plate Lock",
    "拘束具": "Restraint", "蓄力": "Charge", "闪避": "Evasion", "力量": "Strength",
    "灵巧": "Dexterity", "快感": "Arousal", "魔力": "Mana", "能量": "Energy",
    "耐久": "Durability", "紧度": "Tightness", "挣扎": "Struggle", "滑脱": "Slip",
    "伤害": "Damage", "施法": "Cast", "卡组": "Deck", "手牌": "Hand", "卡牌": "Card",
    "普通": "Common", "罕见": "Uncommon", "稀有": "Rare",
}

MANUAL = {
    # Retain the reviewed PR #2 event/schema translations when rebuilding the catalog.
    'conditions 需要1—8条条件。': 'conditions needs 1-8 entries.',
    'has_relic 需要已注册的遗物 id。': 'has_relic needs a registered relic id.',
    'start_node 必须引用已有节点。': 'start_node has to name an existing node.',
    '事件介绍不能为空或过长。': 'The event introduction is empty or too long.',
    '事件必须填写 start_node。': 'The event needs start_node.',
    '事件选项同时携带两种状态条件。': 'The event option carries both state condition spellings.',
    '事件需要1—12个节点。': 'An event needs 1-12 nodes.',
    '单节点事件不得填写 title 或 intro。': 'A single-node event must not declare title or intro.',
    '单节点事件的节点 id 必须为 choice。': 'A single-node event has to use the id choice.',
    '带奖励的选项必须结束事件，不能在领奖后继续下一阶段。': 'A rewarded option has to end the event instead of continuing.',
    '条件模式只支持 optional 或 hidden。': 'A condition mode supports only optional or hidden.',
    '节点 id 无效或重复。': 'A node id is invalid or duplicated.',
    '节点必须填写 allow_refuse 布尔值。': 'Every node has to declare allow_refuse.',
    '节点标题或介绍不正确。': 'A node title or introduction is invalid.',
    '节点的声明取值不正确。': 'A node declaration uses an unsupported value.',
    '节点需要1—6个选项。': 'A node needs 1-6 options.',
    '这段事件已经走过，不能再回头。': 'This event has already happened. You cannot go back.',
    '选项 effects 最多12项。': 'An option takes at most 12 effects.',
    '选项 id、文案或奖励不正确。': 'An option id, label or reward is invalid.',
    '选项 unavailable 只支持 hide 或 disable。': 'An option unavailable value supports only hide or disable.',
    '选项不能同时填写 availability 与 conditions。': 'An option cannot declare both availability and conditions.',
    '选项不能同时填写 recipe 与 effects。': 'An option cannot declare both recipe and effects.',
    '选项不能同时填写 unavailable 与 hide_when_unavailable。': 'An option cannot declare both unavailable and hide_when_unavailable.',
    '选项使用了未知 recipe。': 'An option uses an unknown recipe.',
    '选项条件的事件计数名无效。': 'The option condition counter name is invalid.',
    '选项条件的选择来源：': 'Option condition source: ',
    '选项条件计数必须是0—100整数。': 'An option condition count has to be an integer from 0 to 100.',
    '选项条件需要恰好一个事件计数或选择来源，以及 equals/minimum/maximum。': 'An option condition needs exactly one counter or selector source plus equals/minimum/maximum.',
    '选项至少需要 effects、recipe 或 outcomes。': 'An option needs effects, recipe or outcomes.',
    '选项选择器：': 'Option selector: ',
    "进入新楼层、战斗结束或休整结束时自动保存。继续游戏会回到最近保存的起点；快速SL回到当前场景起点。": "Autosaves occur on entering a higher floor, after battle, or after preparation. Continue restores the last saved start; Quick SL restores the current scene start.",
    "已回到最近保存的起点。": "Returned to the last saved start.",
    "塔路与练习分别保存，重开覆盖对应进度。练习不提供塔路奖励。": "Tower runs and practice save separately. Restarting replaces that mode's progress. Practice grants no tower rewards.",
    "脱缚练习": "Escape Practice",
    "魔力抽调": "Mana Transfer",
    "耐心耐心～": "Patience, Patience~",
    "忍耐": "Endurance",
    "杂鱼♡～杂鱼♡～": "Small Fry♡~ Small Fry♡~",
    "窃取权柄": "Usurp Authority",
    "初始": "Starter",
    "锁定回合结束按钮！": "End Turn is locked!",
    "挣扎%d×%d%s": "Struggle {p0} × {p1} hits{p2}",
    "滑脱%d×%d%s": "Slip {p0} × {p1} hits{p2}",
    "两面合计打出10／20／30／40次后永久进化。本局跨战斗保留；每段分别结算，一张牌只累计1次。": "Permanently evolves after 10/20/30/40 total plays across both faces. Progress persists between battles in this run. Hits resolve separately; each card play counts once.",
    "直到下回合开始，施法预备不会被消耗，也不能用来抵挡拘束。": "Until the start of your next turn, Spell Preparation cannot be consumed or used to evade restraints.",
    "本回合及下回合快感获取量×0.5（命运同担无效）。将1张敏感加入弃牌堆。": "Arousal gain ×0.5 this turn and next turn (does not affect Shared Fate). Add 1 Sensitive to the discard pile.",
    "下回合快感获取量×0.5（命运同担无效）。": "Arousal gain ×0.5 next turn (does not affect Shared Fate).",
    "解除全部拘束与捕缚，清空快感。本回合快感获取量×0.5。": "Remove all restraints and captures. Clear arousal. Arousal gain ×0.5 this turn.",
    "获得3能量、8层魔力预备和3层精神集中，清空快感。本回合快感获取量×0.5。": "Gain 3 Energy, 8 Mana Reserve and 3 Mental Focus. Clear arousal. Arousal gain ×0.5 this turn.",
    "紧度：剩余耐久≤40%为1档，40%～80%为2档，超过80%为3档。": "Tightness: tier 1 at up to 40% durability, tier 2 above 40% through 80%, and tier 3 above 80%.",
    "3档通常免疫普通滑脱；魔法滑脱可突破紧度免疫，但仍受结构限制。": "Tier 3 normally blocks normal slipping. Magic slipping bypasses tightness immunity but still follows structural restrictions.",
    "上锁后：挣扎伤害通常×0.5，不能徒手解除；锁本身不额外禁止滑脱。": "While locked: struggle damage is normally ×0.5 and manual removal is blocked. The lock itself does not block slipping.",
    "嘴部施法：品质倍率×%s；紧度1／2／3档分别×%s／%s／%s。": "Mouth casting: quality ×{p0}; tightness tiers 1/2/3 multiply by ×{p1}/{p2}/{p3}.",
    "本件合计倍率（1／2／3档）：×%s／%s／%s；额外成功率与最低成功率另算。": "Combined multipliers for this item (tiers 1/2/3): ×{p0}/{p1}/{p2}. Additive chance and minimum chance are applied separately.",
    "马具结构禁止普通／魔法滑脱；马具比眼罩更紧时，也会阻止该眼罩滑脱。": "The harness blocks normal and magic slipping. It also blocks slipping off a blindfold that is looser than the harness.",
    "视觉受阻：看不到敌人意图；有一件眼罩仍在就生效。更紧的口球马具会阻止眼罩滑脱。": "Vision blocked: enemy intents are hidden while any blindfold remains. A tighter gag harness blocks blindfold slipping.",
    "大臂／小臂／手腕达到3档时附带躯干固缚；大臂还会附带一对独立肩带。": "Tier 3 restraints on upper arms, forearms, or wrists gain torso bindings. Upper-arm restraints also gain a pair of independent shoulder straps.",
    "%s：耐久%s；%s": "{p0}: durability {p1}; {p2}",
    "肩带剩2条：套体不能滑脱；剩1条：滑脱效果×0.5；全解除：恢复原效果。任意肩带解除后，套体非3档且无外层阻挡，再次挣扎可直接脱下。": "Two shoulder straps block sleeve slipping; one multiplies slipping by 0.5; none restores the normal effect. After one strap is removed, another struggle can remove the sleeve if it is below tier 3 and has no outer obstruction.",
    "肩带左右独立；达到3档后交叉禁滑脱，降至1档才解除此封锁。套体破坏后肩带一并解除。": "Shoulder straps are independent. Reaching tier 3 crosses a strap and blocks slipping until tier 1. Destroying the sleeve also removes its straps.",
    "套体整体滑脱须先解除全部外带，并满足外露、连接与紧度条件。套体破坏后，仍有耐久的外带保留。长至脚趾款封闭脚掌和脚趾。": "Remove all outer bands before slipping off the sleeve, subject to exposure, links, and tightness. Surviving bands remain after the sleeve is destroyed. The toe-length version encloses the feet and toes.",
    "袖部连接与下摆固定都解除后，才可整体滑脱衣身。袖部连接不能滑脱。衣身破坏后，其余组件一并解除；完整衣身封闭双手操作。": "Remove both the sleeve connection and hem fastening before slipping off the jacket. The sleeve connection cannot slip. Destroying the jacket removes its other parts; an intact jacket blocks hand use.",
    "只包裹对应一侧的手掌和手指，各侧最多1件。无独立锁；3档通常免疫普通滑脱。": "Covers only the palm and fingers on its side, at most one per side. No separate lock; tier 3 normally blocks normal slipping.",
    "普通单件仅有向下链接时，普通／魔法滑脱伤害×1.25；多条向下链接不重复加成。链接自身不吃此加成，任一必要端解除时一并移除。": "An ordinary restraint with only downward links gains ×1.25 normal/magic slipping damage, once regardless of link count. Links do not gain this bonus and are removed when either required anchor is removed.",
    "电量耗尽后停止刺激，装备不会自动解除。": "Stimulation stops when the battery runs out; the equipment remains attached.",
    "%s：基础值×部位倍率%s×来源倍率。": "{p0}: base value × body-area multiplier {p1} × source multiplier.",
    "双臂、双腕和双手完全自由时，花费1能量直接取出。": "When both arms, wrists, and hands are completely free, spend 1 energy to remove it directly.",
    "普通挣扎／滑脱需要可用手部辅助，或接触本件支持的借力环境。": "Normal struggle/slipping requires usable hand assistance or contact with an environment supported by this item.",
    "快感上限＋5×（品质＋紧度）；锁外来源快感×［1＋0.05×（品质＋紧度）］。每次高潮后按（品质＋紧度）×保留系数保留快感，系数初始3、每次永久＋1，普通模式最高10。": "Pleasure cap +5 × (quality + tightness); external-source pleasure × [1 + 0.05 × (quality + tightness)]. After climax, retain (quality + tightness) × the retention factor. The factor starts at 3 and permanently increases by 1 each time, capped at 10 in normal mode.",
    "可连接手腕或大腿根装备；对手腕算下端，对大腿根算上端。": "Can link to wrist or upper-thigh equipment; counts as below the wrists and above the upper thighs.",
    "离地%s米的墙缝": "Wall crack {p0} m above the floor",
    "随使用次数和可用条件变化更新": "Updates with remaining uses and availability",
    '开场会束住手腕、口部和脚踝，再准备并施加50/100的捕缚。无法新增或合法替换时，改为加固该处1次；紧度3且可上锁时，上锁并恢复满耐久。用挣扎或滑脱牌削减捕缚；达到100后，警卫下一次行动会收押你。': 'The opening session of the meeting was held with the arm, mouth and ankles.And prepare and impose a 50/100 catch. Draw down the catch with the Struggle or Slip; After reaching 100,The guard will take you on the next move. If a starting slot cannot accept a new or legal replacement restraint, reinforce that slot once. At tightness 3, a lockable restraint is locked and restored to full durability.',
    '开场：手腕、口部、脚踝各施加1件中级2档拘束具；准备1回合后施加捕缚50/100。无法新增或合法替换时，改为加固该处1次；紧度3且可上锁时，上锁并恢复满耐久。\n行动：中级2档普通拘束具×2→捕缚＋10→中级2档复合拘束具×1，循环。复合无法施加时，改为加固至多2件至3档。\n捕缚效果：上身束缚等级至少1；姿态只能躺姿→坐姿→站姿，每次切换捕缚＋10。每次花费能量，使一个随机特殊部位增加10点基础快感（受敏感度影响）；每次高潮捕缚＋10。': "(a) Opening: a second stage of Restraint is imposed on wrists, mouths and ankles; Prepare a turn after which catch 50/100 will be imposed. Action: Common Restraint x 2 + 10 + 2 plus Restraint x 1Loop.This post is part of our special coverage Syria Protests 2011. Reformulated to reinforce up to 2 to 3 items.(b) Catch effects: upper binding levels of at least 1;It's not like I'm going to have to sit and stand. Every time you switch the trap +10. Every time I spend on Energy,(a) Add 10 points to the base of a random special part, Arousal (affected by sensitivity); Every climax +10. If a starting slot cannot accept a new or legal replacement restraint, reinforce that slot once. At tightness 3, a lockable restraint is locked and restored to full durability.",

    "已离开监狱。请选择新塔路第10—11层的任一非休息、非宝箱区域作为起点；保留当前装备、卡组、遗物与资源。新地图的普通战斗全部使用强怪池。": "You have left prison. Choose any room on floors 10–11 of the new tower except rest sites and treasure rooms. Keep your equipment, deck, relics, and resources. All normal battles on this map use the strong encounter pool.",
    "普通战斗 · 强怪池。": "Normal battle · Strong encounter pool.",
    "到期出狱或击败出口守卫后，在新地图第10—11层任一非休息、非宝箱区域开始。新地图的普通战斗从第一场起全部使用强怪池，精英与Boss仍使用各自的遭遇。出口守卫奖励为稀有卡三选一、遗物和60魔瓶魔力。塔内怪物在周目生命倍率后，额外增加（安全等级－1，最低0）×普通10／精英20／Boss30生命。": "After serving your sentence or defeating the exit guards, start in any room on floors 10–11 except rest sites and treasure rooms. All normal battles on the new map use the strong encounter pool from the first battle onward; elites and bosses keep their own encounters. Exit guards award a choice of three rare cards, a relic, and 60 flask mana. After the cycle health multiplier, tower enemies gain max(security level − 1, 0) × 10 health for normal enemies, × 20 for elites, or × 30 for bosses.",
    '双臂受限达到三级': 'Arm restriction level 3',
    '需要双腿活动自由': 'Requires free legs',
    '腿部严密度达到4级': 'Leg restriction level 4',
    '双腿无法独立活动': 'Legs cannot move independently',
    '无力化，无法攻击': 'Weakened: cannot attack',
    '本回合次数已用完': 'No uses left this turn',
    '需要站姿': 'Requires standing',

    "到期出狱练习": "Sentence Release Practice",
    "从正常收押开始，按1级监狱规则佩戴装备并登记；进入牢房后从第1回合开始，初始刑期20回合，巡视间隔16回合。": "Begin with normal intake and registered equipment under level 1 prison rules. Enter the cell on turn 1 with a 20-turn sentence and patrols every 16 turns.",
    "自行挣脱、探索或等待；每次检查有违规最多延长8回合。到期临时检查通过后，才能选择10—11层非休息、非宝箱起点。": "Free yourself, explore, or wait. Violations extend the sentence by up to 8 turns per inspection. Pass the extra inspection at release time to choose a starting room on floors 10–11, excluding rest sites and treasure rooms.",
    "巡视与延期练习": "Patrol and Sentence Extension Practice",
    "同样从正常收押和第1回合开始。可尝试解除已登记装备，观察巡视时的补装和延期；练习不会预设检查结果。": "Also begins with normal intake and turn 1. Try removing registered equipment to observe replacement and sentence extensions during patrols. Inspection results are not preset.",
    "登记装备缺失或检查时工具被没收，当次期限延长8回合。到期另做临时检查，不通过则继续服刑，不重置正常巡视周期。": "Missing registered equipment or confiscated tools extend the sentence by 8 turns per inspection. An extra inspection occurs when the sentence ends; failing it keeps you imprisoned without resetting regular patrol timing.",
    "保留正常收押生成的装备，从出口守卫战开始，守卫使用正常血量。胜利后领取稀有卡三选一、遗物和60魔瓶魔力，再选择10—11层起点。": "Keep normal intake equipment and begin at the exit guard battle with normal guard health. Win to choose one of three rare cards and claim a relic and 60 flask mana, then select a starting room on floors 10–11.",
    '双臂／双腿': 'Arms / Legs',
    '双腿': 'Legs',
    '原角色的基础动作、卡牌与规则保持不变。': 'The original character retains the same basic actions, cards, and rules.',
    '快感－%s': 'Arousal -{p0}',
    '下回合＋%d能量 · %d/%d次': 'Next turn +{p0} Energy · {p1}/{p2} uses',
    '消耗%d能量。': 'Costs {p0} Energy.',

    '援军': 'Reinforcements',
    '已达上限': 'Limit reached',
    '%d回合后抵达': 'Arrives in {p0} turns',
    '每4回合召来1名警卫。已召来%d / %d名；战斗胜利后停止。': 'Summons 1 guard every 4 turns. Summoned: {p0} / {p1}. Stops on victory.',
    '监狱警卫战': 'Prison patrol battle',
    '本场战斗结束时消失': 'Ends with this battle',
    '援军将在4回合后抵达，之后每4回合召来1名警卫；本场最多%d名。': 'Reinforcements arrive in 4 turns, then 1 guard every 4 turns; up to {p0} this battle.',
    '援军抵达：%s加入战斗，从下一回合开始行动。已召来%d / %d名警卫。': 'Reinforcements arrive: {p0} joins the battle and acts from next turn. Guards summoned: {p1} / {p2}.',
    '反抗战斗缺少援军进度，请重新开始此局。': 'Reinforcement progress is missing from this resistance battle. Please start a new run.',
    '援军数量不正确。': 'Invalid reinforcement count.',
    '援军只能出现在牢房内的反抗战斗。': 'Reinforcements are only available in prison patrol resistance battles.',
    '援军尚未到达对应回合。': 'The reinforcement arrival turn has not been reached.',
    '援军出场回合不正确。': 'Invalid reinforcement arrival turn.',

    "到期出狱练习 · 检查通过": "Sentence Completion Practice · Pass Inspection",
    "已服刑19／20回合。结束回合，临时检查通过后选择10—11层起点。": "Served 19/20 turns. End the turn, pass the additional inspection, and choose a starting room on floors 10–11.",
    "临时检查不重置正常巡视周期；起点不能选休息点或宝箱房。": "Additional inspections do not reset regular patrols. Rest and treasure rooms cannot be starting rooms.",
    "到期出狱练习 · 违规延期": "Sentence Completion Practice · Violation Extension",
    "已服刑19／20回合，墙缝中装有尖锐的小石片。直接结束回合，会被没收并延长8回合。": "Served 19/20 turns with a sharp stone shard installed in a wall crack. End the turn to have it confiscated and receive an 8-turn extension.",
    "观察期限变为28回合、正常巡视倒计时继续；再结束8回合，通过下次临时检查后选择10—11层起点。": "Watch the sentence increase to 28 turns while the patrol countdown continues. End 8 more turns, pass the next additional inspection, and choose a starting room on floors 10–11.",
    "击败剩余1生命的出口守卫，领取稀有卡三选一、遗物和60魔瓶魔力，再选择10—11层起点。": "Defeat the exit guard with 1 HP remaining. Claim 1 of 3 Rare cards, a relic, and 60 Flask Mana, then choose a starting room on floors 10–11.",
    "守卫胜利后进入新地图起点选择；休息点和宝箱房不可选。": "Defeating the guard opens starting-room selection for the new map. Rest and treasure rooms cannot be selected.",
    "出狱期限已到，立即进行一次临时巡视检查；本次检查不计入正常巡视周期。": "Your sentence is due. An additional inspection takes place now without changing the normal patrol cycle.",
    "临时巡视检查未通过，出狱期限延长8回合；继续服刑，正常巡视按原周期进行。": "The additional inspection failed. Your sentence is extended by 8 turns. Normal patrols keep their existing schedule.",
    "临时巡视检查通过，按当前安全等级施加出狱装备。你将前往新塔路，选择第10—11层的非休息、非宝箱区域作为起点。": "The additional inspection passed. Release equipment is applied at the current security level. Choose a non-rest, non-treasure room on floors 10–11 of the new tower.",
    "安全等级1／2／3／4：累计20／30／50回合／不自动出狱。牢房、反抗战及其整备均累计；检查确认不计回合。每次检查发现缺装或没收工具，最多延长8回合；正常充电、恢复消耗牌不延长。到期立即执行一次临时巡视检查，不重置正常巡视周期。检查不通过则处罚并延长8回合，下次到期重新检查；通过后按当前安全等级施加出狱装备，再选择新塔路起点。": "Security levels 1/2/3/4: serve 20/30/50 turns or have no automatic release. Cell turns, resistance battles, and their preparation count; inspection confirmations do not. Missing equipment or confiscated tools add at most 8 turns per inspection. Recharging and restoring exhausted cards add no time. When due, an additional inspection runs without resetting normal patrols. A failed inspection applies penalties and extends the sentence by 8 turns; inspect again at the next due date. After passing, apply release equipment at the current security level and choose a starting room.",
    "你的肉棒仍在高潮中一阵阵抽动，马眼却只能流出少量精液。所剩无几的魔力也随这次射精被榨了个干净。": "Your cock keeps twitching through the climax, but only a little semen dribbles from its tip. The scant Mana stored in it is drained dry with this ejaculation.",
    "再回过神时，棕发狱警已经把你按在监狱的登记台前。": "By the time you regain your bearings, the brown-haired guard has pinned you against the prison intake desk.",
    "别乱动。登记完这些，就送你进牢房❤": "Hold still. Once I finish registering all this, you are going straight into your cell❤",
    "最后，她把量杯推到你胯下，隔着手套握住肉棒，从根部一路撸到龟头。没几下，你便在她手里射了出来；精液落进量杯，储存在其中的魔力也被一并榨走。": "Finally, she slides a measuring cup beneath your crotch and strokes your cock through her glove from base to tip. It takes only a few passes before you come in her hand; your semen spills into the cup, carrying the Mana stored within it.",
    "最后，她把量杯推到你胯下，握住肉棒撸到根部。你只断断续续流出一点精液，所剩无几的魔力也被她一并收走。": "Finally, she slides a measuring cup beneath your crotch and strokes your cock down to the base. Only a little semen dribbles out in fits and starts, and she collects the scant Mana remaining in it.",
    "最后，她低头看见肉棒被平板锁压得一点也硬不起来，明显愣了一下，很快又若无其事地揉捏起你的乳房和小穴。锁下的肉棒只能疯狂顶着内壁，精液却还是没用地从缝隙里流进量杯，储存在其中的魔力也被她一并收走。": "Finally, she looks down and pauses at the sight of your cock pinned too flat by the plate lock to harden. She quickly carries on, calmly kneading your breasts and pussy instead. Your trapped cock can only buck frantically against the inside as semen uselessly leaks through the gap into her measuring cup, along with the Mana stored in it.",
    "最后，她低头看见肉棒被平板锁压得一点也硬不起来，明显愣了一下，很快又若无其事地揉捏起你的乳房和小穴。锁下的肉棒徒劳地顶着内壁，最后只从缝隙里断断续续流出一点精液。": "Finally, she looks down and pauses at the sight of your cock pinned too flat by the plate lock to harden. She quickly carries on, calmly kneading your breasts and pussy instead. Your trapped cock thrusts futilely against the inside until only a little semen dribbles through the gap.",
    "她收起量杯，在登记板上盖下印章，随后拽着连接绳把你带到牢门前。": "She puts away the measuring cup, stamps your intake sheet, then leads you to the cell door by the connecting rope.",
    "好了，带着这副样子进去吧❤": "All done. In you go, just like that❤",
    "例行巡视。把手放好，让我看看你有没有偷偷弄掉什么。": "Routine inspection. Keep your hands where I can see them while I check whether you removed anything.",
    "都还在。很好，接下来也别乱动❤": "Everything is still there. Good. Now keep still for the rest of this. ❤",
    "还敢在牢房里藏工具？我替你收起来❤": "Hiding tools in your cell? I will take those off your hands. ❤",
    "少了几件啊？没关系，我会重新给你戴好❤": "A few pieces are missing? That is fine. I will put them back on you. ❤",
    "期限到了？先让我做最后一次检查。": "Your sentence is up? Let me conduct one final inspection first.",
    "好了，今天这一份我收走了。乖乖等下次巡视吧❤": "There. I have collected today's share. Be good and wait for the next patrol❤",
    "已经快被榨空了？那就先到这里，下次巡视再继续❤": "Already nearly drained dry? That will do for now. We can continue at the next patrol❤",
    "肉棒都硬不起来，摸摸别处还是自己流出来了。真没用❤": "Your cock cannot even get hard, yet touching you elsewhere still makes it leak all by itself. How useless❤",
    "都被锁成这样了，还能流出这么一点。真努力啊❤": "Locked down this tightly and you still managed to dribble out that little bit. How diligent❤",
    "手续办完了。身上的东西照旧带走——出去以后，可别这么快又被送回来❤": "The paperwork is done. You will leave with everything still on you—and once you are out, try not to get sent back too soon❤",
    "少了东西还想出去？回去继续待着，等我下次检查。": "You are missing equipment and still expect to leave? Go back and wait for my next inspection.",
    "紫发狱警推开牢门，夹着登记板走到你面前。她扫过你身上的拘束具，又低头核对起入狱时留下的清单。": "The purple-haired guard opens the cell door and approaches with a clipboard tucked under her arm. She looks over your restraints, then checks them against your intake record.",
    "她逐件检查过你身上的拘束与性玩具，确认没有缺少，随后把目光落在你两腿之间。": "She checks every restraint and sex toy on your body. Once she confirms that nothing is missing, her gaze settles between your legs.",
    "她很快找出了缺少的装备，在登记板上添了几笔，又把准备补装的拘束具放到床边。": "She quickly identifies the missing equipment, adds several notes to her clipboard, and places the replacement restraints beside the bed.",
    "她隔着手套握住你的肉棒，拇指压着龟头下沿，一下一下撸到根部。你很快被榨得腰腹发颤，精液接连射进她备好的量杯里。": "She grips your cock through her glove, presses her thumb beneath the head, and strokes down to the base again and again. Your waist soon trembles as she milks you, sending spurt after spurt of semen into her measuring cup.",
    "她仍握着你的肉棒撸到根部。你只断断续续流出一点精液，肉棒便软软抽动着，再也射不出更多。": "She keeps stroking your cock down to the base. Only a little semen dribbles out in fits and starts before it twitches limply, unable to produce any more.",
    "她看见肉棒被平板锁死死压住，先愣了一下，随即坦然地把手伸向你的乳房和小穴。她轮流揉捏几下，锁下的肉棒便疯狂顶着内壁，精液没用地从缝隙里流了出来。": "She pauses when she sees your cock pinned flat inside the plate lock, then calmly reaches for your breasts and pussy. After a few alternating squeezes, your trapped cock thrusts frantically against the inside while semen uselessly leaks through the gap.",
    "她看见肉棒被平板锁死死压住，先愣了一下，随即揉捏起你的乳房和小穴。锁下的肉棒徒劳地顶着内壁，最后只从缝隙里断断续续流出一点精液。": "She pauses when she sees your cock pinned flat inside the plate lock, then begins kneading your breasts and pussy. Your trapped cock thrusts futilely against the inside, until only a little semen dribbles through the gap.",
    "例行巡视的手部榨精": "Manual milking during routine inspection",
    "出狱前巡视的手部榨精": "Manual milking during the pre-release inspection",
    "紫发狱警打开牢门，例行巡视开始。可以接受检查，或立即反抗。": "The purple-haired guard opens the cell door. The routine inspection begins; submit to it or resist at once.",
    "出狱期限已到，资深狱警进入牢房进行额外检查；本次不计入正常巡视周期。": "Your sentence is due. The senior guard enters the cell for an additional inspection; it does not count toward the regular patrol cycle.",
    "出狱前检查未通过，出狱期限延长8回合；继续服刑，正常巡视按原周期进行。": "You failed the pre-release inspection. Your sentence is extended by 8 turns, while regular patrols continue on their existing schedule.",
    "出狱前检查通过，按当前安全等级补齐出狱装备。接下来可以选择新塔路第10—11层的起点。": "You passed the pre-release inspection. Release equipment is applied for your current security level; now choose a starting room on floors 10–11 of the new tower.",
    "棕发狱警核对完登记板，把牢房钥匙收回腰间。当前警戒度：%d。": "The brown-haired guard finishes checking her clipboard and returns the cell key to her belt. Current alert level: {p0}.",
    "牢门在你身后砰地合上。棕发狱警隔着铁栏晃了晃钥匙，这才转身离开。": "The cell door slams shut behind you. The brown-haired guard jingles the key through the bars before finally turning away.",
    "收押完成：警戒度%d；没收道具%d件；新增拘束具%d件、连接绳%d条、性玩具%d件；榨取%s魔力。": "Intake complete: Alert {p0}; {p1} items confiscated; {p2} restraints, {p3} connecting ropes, and {p4} sex toys added; {p5} Mana extracted.",
    " 已戴上限制项圈。": " A Restriction Collar was also locked around your neck.",
    "牢门会在你身后锁上。": "The cell door will lock behind you.",
    "让她核对你身上的装备。": "Let her check the equipment on your body.",
    "让她继续": "Let Her Continue",
    "处理这次检查的结果。": "Let her finish this inspection.",
    "返回牢房": "Return to the Cell",
    "继续服刑。": "Continue serving your sentence.",
    "与她战斗。胜利可取得牢门钥匙。": "Fight her. Win to take the cell key.",
    "少了%d件拘束具。她准备再给你加上%d件%s。": "{p0} restraints are missing. She prepares to put {p1} {p2} on you.",
    "少了%d件性玩具。她又拿来了%d件%s。": "{p0} sex toys are missing. She brings over {p1} {p2}.",
    "一件也没少。": "Not a single piece is missing.",
    "牢房里的%d件工具也被她找到了。": "She also finds the {p0} tools hidden in the cell.",
    "拘束具补回%d/%d件。": "Restraints replaced: {p0}/{p1}.",
    "性玩具补回%d/%d件。": "Sex toys replaced: {p0}/{p1}.",
    "没收工具%d件。": "Tools confiscated: {p0}.",
    "%d件性玩具已经充好电。": "Sex toys recharged: {p0}.",
    "刑期＋%d回合。": "Sentence +{p0} turns.",
    "检查结束。": "Inspection complete.",
    "收押时的手部榨精": "Manual milking during intake",
    "监狱收押": "Prison Intake",
    "✓  收押完成": "✓  Intake Complete",
    "警戒度 %d　·　没收道具 %d件　·　榨取魔力 %s": "Alert {p0}　·　Items confiscated {p1}　·　Mana extracted {p2}",
    "棕发狱警把你押到牢门前，逐件收紧新添的拘束，最后在登记板上盖下印章。": "The brown-haired guard marches you to the cell, tightens each new restraint, then stamps the intake sheet.",
    "她将「{name}」从你的手指一路套上双臂，理平套体后逐条收紧肩带。双臂被牢牢包在一起，连手指也只能隔着紧绷的材质徒劳蜷动。": "She pulls {p0} over your hands and up both arms, smooths the sleeve, then tightens each shoulder strap. Your arms are sealed together, leaving even your fingers able to flex only uselessly beneath the taut material.",
    "她把「{name}」套上你的双腿，沿着大腿、小腿一路收紧外带。两条腿被整件拘束具并在一起，只能勉强挪动。": "She pulls {p0} over both legs and tightens its outer straps along your thighs and calves. The restraint pins your legs together, leaving you barely able to shuffle.",
    "她把「{name}」套到你身上，将双臂折进封闭的袖筒，再扣紧衣身与下摆。你的手被压在身后，肩膀也难以抬起。": "She fits {p0} around you, folds your arms into its closed sleeves, then fastens the body and hem. Your hands are pinned behind you and even lifting your shoulders becomes difficult.",
    "她合拢你的手掌与手指，用「{name}」一层层裹紧。整只手被包得严严实实，指节再也无法分开。": "She presses your palm and fingers together, wrapping them layer by layer in {p0}. Your entire hand is sealed tight, and your knuckles can no longer spread apart.",
    "她把「{name}」套到你身上，逐一收紧外侧的固定带，将覆盖的部位牢牢拘束起来。": "She fits {p0} around your body and tightens each outer strap, firmly restraining every covered area.",
    "她又将「%s」扣在两件拘束具之间，拉紧后才把余绳盘回腰侧。": "She clips {p0} between two restraints, pulls it taut, then coils the spare length at her hip.",
    "再次挑战": "Retry",
    "重新开始": "Restart",
    "其他练习": "Other Practice",
    "放弃战斗，被逮捕并进入收押处理。": "Give up the fight, be captured, and proceed to prison intake.",
    "例行巡视": "Routine Inspection",
    "巡视结束": "Inspection Over",
    '力量＋2。回合开始时，快感＋5。': 'Strength +2. At the beginning of the turn, Arousal +5.',
    '秘密武器': 'Secret Weapon',
    '秘密武器：脚趾也被拘束，不能代替手部施法。': 'Secret Weapon: your toes are also bound and cannot replace your hands for casting.',
    '秘密武器：脚趾被拘束，脚趾施法成功率×0%。': 'Secret Weapon: bound toes have a 0% casting success rate.',
    '脚趾（代替手部）': 'Toes (replacing hands)',
    '秘密武器：手部%s，脚趾%s，取较高成功率。': 'Secret Weapon: hands {p0}, toes {p1}; use the higher success rate.',
    '秘密武器：脚趾代替手部施法。': 'Secret Weapon: cast with toes instead of hands.',
    '秘密武器：脚趾代替手部，获得手势加成。': 'Secret Weapon: toes replace hands and grant the gesture bonus.',
    '秘密武器：脚趾牵扯增加%s快感值。': 'Secret Weapon: toe traction adds {p0} arousal.',
    '秘密武器·脚趾牵扯': 'Secret Weapon · Toe Traction',
    '脚趾牵扯': 'Toe Traction',
    '%s：%s、紧度%d档，基础快感＋%s。': '{p0}: {p1}, tightness tier {p2}, base arousal +{p3}.',
    '每次消耗能量时触发一次；额外牵扯也会触发。': 'Triggers once per energy-spending action, and on additional traction.',
    '脚趾施法成功率×0%；解除脚趾拘束后停止。': 'Toe casting success is 0%; ends when your toes are freed.',
    '脚趾被拘束时': 'While toes are bound',
    '＋%s快感': '+{p0} arousal',
    '脚趾可代替手部施法，取两者较高成功率。脚趾被拘束时不能施法，并产生牵扯。等级＋紧度为2／3／4／5／6时，每次牵扯基础快感＋1／2／3／4／6，多件累加；脚趾被拘束的优先级提高至与嘴部相同，仅次于手腕。': 'Toes can replace hands for casting; use the higher success rate. Bound toes cannot cast and cause traction. For grade + tightness of 2/3/4/5/6, each traction adds 1/2/3/4/6 base arousal; multiple pieces add together. Toe restraint priority rises to the mouth tier, below wrists.',

    '上身拘束严密度': 'Upper-body tightness',
    '腿部拘束严密度': 'Leg tightness',
    '自缚': 'Self-Binding',
    '随机收紧拘束具共2X档，不上锁。随后恢复15X自身魔力。空间不足时无法使用。': 'Randomly tighten restraints by a total of 2X tiers without locking them. Then restore 15X personal Mana. Cannot be played unless the full tightening is possible.',
    '腿部随机佩戴2件拘束具，每件品质＋紧度＝2X。随后恢复15X自身魔力。空间不足时无法使用。': 'Equip 2 random leg restraints, each with quality + tightness = 2X. Then restore 15X personal Mana. Cannot be played unless both restraints fit.',
    'X为打出前的全部剩余能量。主动佩戴不触发闪避或蓄力抵挡，不替换已有装备。自由面X需为1—3；拘束面X＝0时无效果。复放沿用原X并重新检查空间。': 'X is all remaining Energy before playing. Voluntary equipping does not trigger Evasion or charge-based blocking and never replaces equipment. The free face requires X from 1 to 3; the bound face has no effect at X = 0. Replays retain the original X and recheck available capacity.',
    '当前X＝%d，没有品质＋紧度＝%d的拘束具。': 'At X = {p0}, no restraint has quality + tightness = {p1}.',
    '腿部没有足够位置完整佩戴2件符合要求的拘束具。': 'There is not enough leg capacity to equip both required restraints.',
    '需要收紧%d档，当前最多只能收紧%d档；无法完整执行。': 'Requires {p0} tiers of tightening, but only {p1} are available. The full effect cannot be completed.',
    '当前X＝%d：%s随后恢复%d自身魔力。': 'Current X = {p0}: {p1} Then restore {p2} personal Mana.',
    '每件品质＋紧度＝%d。': 'Each restraint has quality + tightness = {p0}.',
    '随机收紧共%d档，不上锁。': 'Randomly tighten by a total of {p0} tiers without locking.',
    '自缚：在%s佩戴%s（%s，紧度%d档）。': 'Self-Binding: equipped {p1} on {p0} ({p2}, tightness tier {p3}).',
    '自缚：%s紧度%d → %d档。': 'Self-Binding: {p0} tightness tier {p1} → {p2}.',
    '自缚：X＝%d，恢复%s自身魔力。': 'Self-Binding: X = {p0}; restored {p1} personal Mana.',
    '自缚需要X费自身技能配置。': 'Self-Binding requires an X-cost self-targeted skill definition.',
    '自缚的收紧、回魔或腿部装备配置不正确。': 'Invalid Self-Binding tightening, Mana recovery, or leg equipment configuration.',
    '巡视中：仅可检查或反抗。发现违规时，每次检查最多延长8回合。': 'During inspection, you can only submit to inspection or resist. A violation extends your sentence by at most 8 turns per inspection.',
    '出狱期限已到，按当前安全等级重新检查并施加装备。你将前往新塔路，选择第10—11层的非休息、非宝箱区域作为起点。': 'Your sentence is complete. Equipment is checked and applied using the current security level. Choose a non-rest, non-treasure room on floors 10–11 of the new tower.',
    '已离开监狱。请选择新塔路第10—11层的任一非休息、非宝箱区域作为起点；保留当前装备、卡组、遗物与资源。': 'You have left prison. Choose any non-rest, non-treasure room on floors 10–11 of the new tower. Keep your current equipment, deck, relics, and resources.',
    '监狱出口的警卫已全部被击败。收取战利品后，选择新塔路第10—11层的非休息、非宝箱区域开始。': 'All exit guards have been defeated. Claim your rewards, then choose a non-rest, non-treasure room on floors 10–11 of the new tower.',
    '出狱起点只能选择第10—11层的非休息、非宝箱区域。': 'Your starting room after release must be a non-rest, non-treasure room on floors 10–11.',
    '出狱后，在新塔路第10—11层选择非休息、非宝箱区域开始。': 'After release, choose a non-rest, non-treasure room on floors 10–11 of the new tower.',
    '选择出狱起点 · 第10—11层非休息、非宝箱区域 · 不消耗回合': 'Choose Your Starting Room · Floors 10–11, No Rest or Treasure Rooms · No Turn Cost',
    '请选择第10—11层的非休息、非宝箱区域作为出狱起点。': 'Choose a non-rest, non-treasure room on floors 10–11 as your starting room after release.',
    '继续后选择第10—11层的非休息、非宝箱区域开始。': 'Continue to choose a non-rest, non-treasure starting room on floors 10–11.',
    '到期出狱或击败出口守卫后，在新地图第10—11层任一非休息、非宝箱区域开始。出口守卫奖励为稀有卡三选一、遗物和60魔瓶魔力。塔内怪物在周目生命倍率后，额外增加（安全等级－1，最低0）×普通10／精英20／Boss30生命。': 'After completing your sentence or defeating the exit guards, start in any non-rest, non-treasure room on floors 10–11 of the new map. Exit guards award a choice of 1 of 3 Rare cards, a relic, and 60 Flask Mana. After applying the continued-run health multiplier, tower enemies gain max(0, security level − 1) × 10/20/30 HP for normal/elite/Boss encounters.',
    '本次检查延长出狱期限%d回合。': 'This inspection extends your sentence by {p0} turns.',
    '已服刑%d回合 · 不自动出狱': 'Served {p0} turns · No automatic release',
    '已服刑%d／%d回合 · 出狱剩余%d回合': 'Served {p0}/{p1} turns · Release in {p2} turns',
    '出狱期限记录不正确。': 'Invalid sentence progress.',
    '出狱期限已到，按当前安全等级重新检查并施加装备。你将前往新塔路，选择第10—11层的非休息区域作为起点。': 'Your sentence is complete. Equipment is checked and applied using the current security level. Choose a non-rest room on floors 10–11 of the new tower.',
    '已离开监狱。请选择新塔路第10—11层的任一非休息区域作为起点；保留当前装备、卡组、遗物与资源。': 'You have left prison. Choose any non-rest room on floors 10–11 of the new tower. Keep your current equipment, deck, relics, and resources.',
    '监狱出口的警卫已全部被击败。收取战利品后，选择新塔路第10—11层的非休息区域开始。': 'All exit guards have been defeated. Claim your rewards, then choose a non-rest room on floors 10–11 of the new tower.',
    '选择此区域作为出狱起点，不消耗回合。\n': 'Start here after release. This choice costs no turns.\n',
    '从这里开始 · ': 'Start here · ',
    '出狱起点只能选择第10—11层的非休息区域。': 'Your starting room after release must be a non-rest room on floors 10–11.',
    '作为新塔路起点。': ' as your starting room in the new tower.',
    '出狱起点选择阶段不正确。': 'Invalid post-release starting-room selection.',
    '到期出狱练习': 'Sentence Completion Practice',
    '击败守卫出狱练习': 'Exit Guard Victory Practice',
    '出狱后，在新塔路第10—11层选择非休息区域开始。': 'After release, choose a non-rest room on floors 10–11 of the new tower.',
    '结束一回合即可到期出狱。': 'End this turn to complete your sentence.',
    '击败剩余1生命的出口守卫，领取正式奖励后选择起点。': 'Defeat the exit guard with 1 HP remaining, claim the regular rewards, then choose your starting room.',
    '稀有卡三选一': 'Choose 1 of 3 Rare Cards',
    '出口守卫奖励': 'Exit Guard Reward',
    ' · 存入贴身魔瓶': ' · Stored in your Mana Flask',
    '选择出狱起点 · 第10—11层非休息区域 · 不消耗回合': 'Choose Your Starting Room · Floors 10–11, No Rest Rooms · No Turn Cost',
    '领取出口守卫奖励，贴身魔瓶获得%d魔力。': 'Exit guard reward claimed: your Mana Flask gains {p0} Mana.',
    '请选择第10—11层的非休息区域作为出狱起点。': 'Choose a non-rest room on floors 10–11 as your starting room after release.',
    '继续后选择第10—11层的非休息区域开始。': 'Continue to choose a non-rest starting room on floors 10–11.',
    '选择出狱起点': 'Choose Your Starting Room',
    '出狱期限': 'Prison Sentence',
    '出狱后的新塔路': 'The Tower After Release',
    '玩偶的安全等级生命加成不正确。': 'Invalid security-level health bonus for the puppet.',
    '安全等级1／2／3／4：累计20／30／50回合／不自动出狱。牢房、反抗战及其整备均累计；检查确认不计回合。每次检查发现缺装或没收工具，最多延长8回合；正常充电、恢复消耗牌不延长。到期按当前安全等级执行一次入狱装备判定，再选择新塔路起点。': 'Security levels 1/2/3/4: serve 20/30/50 turns or have no automatic release. Cell turns, resistance battles, and their preparation turns count; inspection confirmations do not. Each inspection involving missing equipment or confiscated tools adds at most 8 turns. Recharging equipment and restoring exhausted cards add no time. At release, apply the current security level’s intake equipment rules once, then choose a starting room in the new tower.',
    '到期出狱或击败出口守卫后，在新地图第10—11层任一非休息区域开始。出口守卫奖励为稀有卡三选一、遗物和60魔瓶魔力。塔内怪物在周目生命倍率后，额外增加（安全等级－1，最低0）×普通10／精英20／Boss30生命。': 'After completing your sentence or defeating the exit guards, start in any non-rest room on floors 10–11 of the new map. Exit guards award a choice of 1 of 3 Rare cards, a relic, and 60 Flask Mana. After applying the continued-run health multiplier, tower enemies gain max(0, security level − 1) × 10/20/30 HP for normal/elite/Boss encounters.',
    '主体': 'Main piece',
    '每场战斗中，每累计消耗30魔力，获得1能量。': 'During each battle, gain 1 Energy for every 30 Mana spent.',
    '头颈': 'Head & Neck',
    '手胸': 'Arms & Chest',
    '臀腿': 'Hips & Legs',
    '性器': 'Intimate',
    '%s · 解缚': '{p0} · Release',
    '同部位由外到内 · 选择装备查看可用方法': 'Outer to inner at each body part · Select equipment for methods',
    '外层': 'Outer',
    '内层': 'Inner',
    '附属': 'Attached',
    '外层覆盖：%s': 'Covered by: {p0}',
    '自由：%s': 'Free: {p0}',
    '耐久 %s / %s · 紧度%d档': 'Durability {p0} / {p1} · Tightness {p2}',
    '装备说明 ＋': 'Equipment info +',
    '效果详情 ＋': 'Effect details +',
    '已上锁 → 已开锁': 'Locked → Unlocked',
    '开锁后，双臂自由时可取下。': 'Once unlocked, remove when both arms are free.',
    '耐久与紧度不变。': 'Durability and tightness unchanged.',
    '整件取下': 'Remove equipment',
    '解除该部件': 'Remove this component',
    '解除连接': 'Remove connection',
    '同时取下%s。': 'Also remove {p0}.',
    '施法成功时': 'On successful cast',
    '三档紧度 · 普通滑脱无效': 'Tightness 3 · Normal slip has no effect',
    '锁具 ×%s': 'Lock ×{p0}',
    '目标限制 ×%s': 'Target modifier ×{p0}',
    '紧度 ×%s': 'Tightness ×{p0}',
    '堆叠 ×%s': 'Stacking ×{p0}',
    '部位 ×%s': 'Body part ×{p0}',
    '紧度 %d档 → %d档': 'Tightness {p0} → {p1}',
    '耐久 %s → %s': 'Durability {p0} → {p1}',
    '头颈  %d  ›': 'Head & Neck  {p0}  ›',
    '头颈  %d  −': 'Head & Neck  {p0}  −',
    '手胸  %d  ›': 'Arms & Chest  {p0}  ›',
    '手胸  %d  −': 'Arms & Chest  {p0}  −',
    '臀腿  %d  ›': 'Hips & Legs  {p0}  ›',
    '臀腿  %d  −': 'Hips & Legs  {p0}  −',
    '性器  %d  ›': 'Intimate  {p0}  ›',
    '性器  %d  −': 'Intimate  {p0}  −',
    '战斗初始距墙1—4格；休息房和牢房从墙边开始。\n“向墙移动”每次1—2格、消耗1—3能量，按姿态和行动能力决定。到墙后获得“贴墙”，移动不自动结束回合。被捕缚时无法移动，先解除捕缚。': 'The initial distance of the fighting was 1-4 cells; the restrooms and cells began at the side of the wall. “Travel to the wall” was 1-2 cells, consuming 1-3 Energy, depending on attitude and mobility. You cannot move while captured. Break free first.',
    '被捕缚时无法移动，先解除捕缚。挣扎／滑脱牌可直接削减进度；除眼罩、口球外没有其他拘束具时伤害翻倍，不受环境加成。上身受限至少按1级计算。同种捕缚不叠加；新种类增加其初始值的一半。降至0全部解除，达到100后下一敌方回合执行收押。': 'You cannot move while captured. Break free first. Struggle / Slip can reduce progress directly; when there are no other Restraint s other than eye patches and mouthballs, Damage doubles, not added to the environment. Upper limit is calculated at least level 1. The same catch is not folded. The new category increases by half its initial value. It drops to zero, and after 100, the next enemy is taken into custody.',
    '解除捕缚：挣扎／滑脱牌可削减进度，不含环境加成；仅有眼罩、口球或没有拘束具时伤害×2。归零后解除，敌人会准备1回合再施加。\n捕缚规则：被捕缚时无法移动，先解除捕缚。同种不叠加；异种共用进度，新种只增加其初始值的一半。达到100后，施加捕缚的敌人在下次行动收押。击败来源解除对应效果，全部来源离场则清空进度。': 'You cannot move while captured. Break free first. Disarm the catch: Struggle / Slip can reduce progress without environmental additions; only blindfolds, mouthballs or, without Restraint, Damage x 2. When released, the enemy prepares a turn for re-enforcement.',
    '被捕缚时无法移动，先解除捕缚。': 'You cannot move while captured. Break free first.',
    '进入监狱时不会丢失。': 'Not lost when entering prison.',
    '收押至监狱，保留原装备与传送符、没收其他道具并追加装备；随后榨精一次，立即损失最多20魔力。无战斗奖励，战斗结束遗物照常触发。': 'Sent to prison: keep existing equipment and the Teleport Seal; other items are confiscated and more equipment is added. You are then milked once and immediately lose up to 20 Mana. No battle rewards; end-of-battle relics still trigger.',
    '入狱保留装备、卡组、遗物和快感，保留传送符、没收其他道具，并追加监狱装备。收押时狱警会榨精一次，立即取走最多20魔力；没有战斗奖励。\n警戒度初始1，每次再次入狱提高，最高5；越高装备越强、检查越频繁。': 'Entering prison preserves equipment, deck, relics, arousal, and the Teleport Seal. Other items are confiscated and prison equipment is added. During intake, a guard milks you once and immediately extracts up to 20 Mana; there is no battle reward.\nSecurity starts at 1 and rises on each subsequent imprisonment, up to 5. Higher security means stronger equipment and more frequent inspections.',
    '捕缚存在时，每次花能量都会牵动一个随机特殊部位；只能依次从躺姿坐起、再站起，且每次切换使进度＋10。击败全部警卫获得正常奖励；被收押则保留装备与快感，收押时榨精并损失最多20魔力；传送符保留，其他道具没收。': 'While captured, each energy spent stimulates a random special body part. You can only move from lying to sitting, then standing; each change adds 10 capture progress. Defeat all guards for normal rewards. If imprisoned, keep equipment and arousal; intake milking costs up to 20 Mana. The Teleport Seal is retained and other items are confiscated.',

    '施加初级2档、加固、准备、附着中级3档并离场。预告加固时若无目标，改为预告自身的施加行动；出手时再选目标，加固已无目标则空过。': 'Apply basic tier-2 equipment, reinforce, prepare, then attach medium tier-3 equipment and leave. If no reinforcement target exists when planning, announce an application instead. Targets are chosen on execution; reinforcement with no remaining target is skipped.',
    '口球准备两回合后附着中级3档并离场；口部已有装备时不会覆盖。': 'After preparing for two turns, attach a medium tier-3 gag and leave. Existing mouth equipment is not replaced.',
    '预告上锁、上锁，两步循环。开启平板锁池时，无目标后尝试附加中级3档负数平板锁及其加固带再离场；无法佩戴仍离场。': 'Announce locking, then lock, repeatedly. With the plate-lock pool enabled, once no target remains, attempt to equip a medium tier-3 Negative Plate Lock and its reinforcement band, then leave even if installation fails.',

    "魔路精通": "Mana Circuit Mastery",
    "魔路精通·自由": "Mana Circuit Mastery - Free",
    "魔路精通·拘束": "Mana Circuit Mastery - Bound",
    "本次耗魔全部由临时魔力支付时，施法失败不返还魔力，改为获得1能量。0费牌每回合最多触发2次。两面互斥。唯一。": "If the entire Mana cost is paid with temporary Mana, a failed cast refunds no Mana and grants 1 Energy instead. Zero-cost cards can trigger this twice per turn. The two faces are mutually exclusive. Unique.",
    "上身、腿部束缚等级均≥2时，施法失败返还100%耗魔并获得1能量；0费牌每回合最多触发2次。两者均≥3时取消该次数限制，条件实时检测。两面互斥。唯一。": "While upper-body and leg restraint levels are both at least 2, failed casts refund 100% of Mana spent and grant 1 Energy. Zero-cost cards can trigger this twice per turn. When both levels are at least 3, the limit is removed. Conditions update dynamically. The two faces are mutually exclusive. Unique.",
    "施法失败返还100%耗魔并获得1能量。0费牌每回合最多触发2次；上身、腿部束缚等级均≥3时不限次数。实时检测。": "Failed casts refund 100% of Mana spent and grant 1 Energy. Zero-cost cards can trigger this twice per turn; unlimited while upper-body and leg restraint levels are both at least 3. Checked dynamically.",
    "本次耗魔全部为临时魔力时，施法失败不返还魔力，改为获得1能量。0费牌每回合最多触发2次。": "If the entire Mana cost is temporary Mana, failed casts refund no Mana and grant 1 Energy instead. Zero-cost cards can trigger this twice per turn.",
    "两面互斥。0费按本次实际能量费用判定；达到次数上限后恢复普通失败返还50%魔力。": "The two faces are mutually exclusive. Zero cost refers to the actual Energy cost. After reaching the limit, failed casts return to the normal 50% Mana refund.",
    "失败默认返还本次耗魔的50%，自身与临时魔力各退回原池": "Failed casts normally refund 50% of Mana spent, returning personal and temporary Mana to their respective pools",
    "次数用完后恢复普通50%返还": "After the limit is reached, the normal 50% refund applies",
    "0费不限次数": "Zero-cost triggers: unlimited",
    "0费剩余%d次": "Zero-cost triggers remaining: {p0}",
    "全临时耗魔失败：能量＋1": "Failed cast paid entirely with temporary Mana: +1 Energy",
    "失败返还100% · 能量＋1": "Failed cast: 100% refund, +1 Energy",
    "两面互斥：本场已启用「%s」，不能再次启用任一面。": "Mutually exclusive: {p0} is already active this encounter. Neither face can be activated again.",
    "魔路精通：获得%d能量。": "Mana Circuit Mastery: gain {p0} Energy.",
    "能力牌的本回合失败计数不正确。": "The power card has an invalid failed-cast counter for this turn.",
    "互斥的能力牌不能同时生效。": "Mutually exclusive powers cannot be active together.",
    "这张能力没有失败次数限制。": "This power does not track limited failed-cast triggers.",
    "能力牌的本回合失败记录损坏。": "The power card has a damaged failed-cast record for this turn.",
    '行动：初级2档拘束具→加固→准备→中级3档拘束具，随后离场。': 'Actions: apply basic tier-2 equipment, reinforce, prepare, then apply medium tier-3 equipment and leave.',
    '行动：准备2回合→施加中级3档口球，随后离场。口部已被占用时不生效。': 'Actions: prepare for 2 turns, apply a medium tier-3 gag, then leave. No effect if the mouth slot is occupied.',
    '行动：预告上锁→上锁，循环。开启平板锁池时，无上锁目标后固定尝试附加中级3档负数平板锁及其加固带再离场，不受概率设置影响；无法佩戴仍离场。关闭时沿用原上锁与无目标结束规则。': 'Actions: announce locking, then lock, repeatedly. With the plate-lock pool enabled, once no locking target remains, attempt to equip a medium tier-3 Negative Plate Lock with its reinforcement band, then leave. This ignores the pool probability; failed installation still ends in departure. With the pool disabled, the original locking and encounter-end rules apply.',
    '附加中级3档平板锁，随后离场': 'Apply a medium tier-3 Plate Lock, then leave',

    "每佩戴%d件拘束具，本回合获得1点力量，不足%d件不计。": "For every {p0} restraints worn, gain 1 Strength this turn. Fewer than {p1} do not count.",
    "每佩戴%d件拘束具，恢复1点魔力。": "For every {p0} restraints worn, restore 1 Mana.",
    "每佩戴%d件拘束具，本回合获得1点力量，不足%d件不计。\n当前：本回合力量＋%s。": "For every {p0} restraints worn, gain 1 Strength this turn. Fewer than {p1} do not count.\nCurrent: +{p2} Strength this turn.",
    "每佩戴%d件拘束具，恢复1点魔力。\n当前：恢复%s魔力。": "For every {p0} restraints worn, restore 1 Mana.\nCurrent: restore {p1} Mana.",
    '限制项圈': 'Restriction Collar',
    '无耐久': 'No durability',
    '先开锁，双臂自由后取下': 'Unlock first, then remove with both arms free.',
    '限制项圈没有耐久，须先开锁，再在双臂自由时取下；品相完美版 henshin 可直接解除。': 'The Restriction Collar has no durability. Unlock it, then remove it with both arms free. Perfect henshin can remove it directly.',
    '限制项圈不能通过耐久变化松解。': 'The Restriction Collar cannot be loosened by changing durability.',
    '已经佩戴限制项圈。': 'A Restriction Collar is already equipped.',
    '不能重复佩戴限制项圈。': 'Only one Restriction Collar can be equipped.',
    '佩戴限制项圈时不能使用 henshin；品相完美版不受影响。': 'The Restriction Collar prevents henshin. Perfect henshin is unaffected.',
    '先用开锁术或开锁工具打开限制项圈的锁。': 'Unlock the Restriction Collar with an unlocking spell or tool first.',
    '双臂需要完全自由才能取下限制项圈。': 'Both arms must be fully free to remove the Restriction Collar.',
    '取下限制项圈': 'Remove Restriction Collar',
    '取下已开锁的限制项圈，花费1能量。': 'Remove the unlocked Restriction Collar for 1 Energy.',
    '取下了已开锁的限制项圈。': 'Removed the unlocked Restriction Collar.',
    '打开限制项圈的锁；双臂自由后可取下。': 'Unlock the Restriction Collar. It can then be removed with both arms free.',
    '位置：颈部\n无耐久 · 不计入拘束具件数\n佩戴时不能使用普通 henshin。\n': 'Location: Neck\nNo durability; excluded from restraint counts.\nPrevents normal henshin while equipped.\n',
    '已开锁 · 双臂自由后可取下': 'Unlocked; removable with both arms free',
    '3级及以上入狱时固定佩戴，不计入件数。\n佩戴时无法使用普通 henshin。\n': 'Automatically equipped on imprisonment at security level 3 or higher; excluded from restraint counts.\nPrevents normal henshin while equipped.\n',
    '拘束具保底%d件，不足时补齐并额外增加%d件、全部至少2档；已达保底则不补装，全部收紧1档，最多3档。另加%d件2档特殊装备，空位不足不替换。': 'Minimum {p0} restraints. Below the minimum, fill to it and add {p1} more, all at least tier 2. At or above it, add none and tighten each by 1 tier, capped at 3. Add {p2} tier-2 special items to free slots only; existing items are not replaced.',
    '五级进入高安全监室。': 'Level 5 leads to the high-security ending.',
    '原有拘束具收紧1档，最多3档。': 'Existing restraints tighten by 1 tier, capped at 3.',
    '普通与复合拘束具收紧至至少2档。': 'Ordinary and composite restraints tighten to at least tier 2.',
    '即将转入高安全监室。': 'Transfer to the high-security cell follows.',
    '执行收押。警戒度升至%d，没收%d件道具；追加%d件拘束具、%d条链接和%d件特殊装备。': ' completes the arrest. Security rises to {p0}. Confiscated {p1} items; added {p2} restraints, {p3} links and {p4} special items.',
    '佩戴限制项圈。': 'Restriction Collar equipped.',
    '3级起固定佩戴限制项圈，不占件数。': 'At level 3 or higher, a Restriction Collar is equipped separately and does not count toward the minimum.',
    '携带卡组与遗物继续游玩仍累计；新开游戏归零': 'Retained when continuing with your deck and relics; reset only in a new game',
    '新的塔路已展开。第%s阶段：怪物基础生命×%s，可解除的装备已解除，魔力已补满；快感降低%s，姿势变为站立。': 'A new tower awaits. Stage {p0}: base enemy HP x{p1}. Eligible equipment was removed and Mana refilled; Arousal decreased by {p2}, and you are standing.',
    '保留卡组、遗物、成长与监狱警戒度，开启全新塔路。怪物基础生命×%s；解除可解除的装备并补满魔力，快感降低%s（最低0），姿势变为站立。': 'Start a new tower while keeping your deck, relics, growth and prison security. Base enemy HP x{p0}; remove eligible equipment, refill Mana, reduce Arousal by {p1} (minimum 0), and stand up.',
    '没收%d件道具，清除临时增益。追加%d件拘束具、%d条链接、%d件特殊装备。': 'Confiscated {p0} items and cleared temporary buffs. Added {p1} restraints, {p2} links and {p3} special items.',
    '限制项圈不计入件数；开锁后须双臂自由才能取下，品相完美版 henshin 可直接解除。': 'The Restriction Collar is excluded from restraint counts. Unlock it and free both arms to remove it; Perfect henshin can remove it directly.',
    '警戒度达到5，移入高安全监室。原装备结构与链接保留，普通与复合装备补齐至高级三档，可上锁处全部上锁；限制项圈继续保留。本次逃脱结束，可以检查最终装备或重新开始。': 'Security reaches level 5. Transfer to the high-security cell preserves existing structures and links, fills ordinary and composite restraints to advanced tier 3, and locks every lockable piece. The Restriction Collar remains equipped. This escape attempt has ended; inspect your equipment or start a new game.',
    '高安全监室：共%d件普通装备、组件与链接，全部高级三档（%s/%s耐久），可上锁处全部上锁。另佩戴无耐久的限制项圈。本局已经结束，可在左侧逐件检查。': 'High-security cell: {p0} ordinary pieces, components and links, all advanced tier 3 ({p1}/{p2} durability), with every lockable piece locked. A durability-free Restriction Collar is equipped separately. This run has ended; inspect individual pieces on the left.',
    '高安全监室的限制项圈必须上锁。': 'The Restriction Collar must be locked in the high-security cell.',
    '%d级：保底%d件，额外%d件，特殊装备%d件。': 'Level {p0}: minimum {p1} restraints, {p2} extra restraints, {p3} special items.',
    '警戒度与入狱': 'Security and Imprisonment',
    '每次入狱，警戒度＋1；携带卡组和遗物继续游玩也会保留，只有新开游戏归零。\n': 'Each imprisonment raises Security by 1. Continuing with your deck and relics preserves it; only a new game resets it.\n',
    '\n普通和复合拘束具按整件计数。不足保底时补齐并额外增加，全部至少2档；已达保底则不补装，全部收紧1档，最多3档。特殊装备以2档添加，空位不足不替换。\n3级起固定佩戴限制项圈，不占件数；须先开锁，再在双臂自由时取下。佩戴时禁止普通 henshin，品相完美版可以使用并直接解除项圈。\n检查补装的等级与紧度：\n': '\nCount each ordinary restraint or active composite root once. Below the minimum, fill to it and add the extra amount; all pieces become at least tier 2. At or above the minimum, add none and tighten each by 1 tier, capped at 3. Add tier-2 special equipment only to available slots, without replacement.\nFrom level 3, a separate Restriction Collar is equipped and excluded from the count. Unlock it, then remove it with both arms free. It blocks normal henshin, but Perfect henshin can remove it directly.\nInspection replacement grades and tiers:\n',
    '\n3级起可出现复合装备，每套占1个名额。5级进入高安全监室。': '\nComposite restraints become available from level 3; each whole set counts once. Level 5 leads to the high-security cell.',
    # Follow-up pass: high-frequency UI, rule and narrative strings that the
    # compact model translated literally or with the wrong gameplay meaning.
    "柔软硅胶": "Soft silicone",
    "弱怪": "Lesser Enemy",
    "成功：获得一件随机遗物。": "Success: Gain a random relic.",
    "【离开】放弃继续尝试": "[Leave] Give Up",
    "你放弃继续尝试，带着已经缠到身上的拘束具离开了回廊。": "You stop trying and leave the corridor with the restraints already wrapped around you.",
    "自由": "Free",
    "硅胶与塑料": "Silicone and plastic",
    "捕缚": "Capture",
    "获得「": "Gain “",
    "领取「": "Claim “",
    "获得": "Gain",
    "精英": "Elite",
    "强怪练习": "Strong Enemy Practice",
    "诅咒眼罩封闭了眼部装备操作。": "The cursed blindfold prevents interaction with eye equipment.",
    "需要先到牢门前。": "Move in front of the cell door first.",
    "绳索": "Rope",
    "链接绳": "Link Rope",
    "已跳过": "Skipped",
    "诅咒": "Curse",
    "事件": "Event",
    "加固拘束具": "Reinforce Restraint",
    "上锁": "Lock",
    "加固": "Reinforce",
    "跳过": "Skip",
    "遗物": "Relic",
    "已解除。": "Removed.",
    "药剂": "Potion",
    "卷轴": "Scroll",
    "牢门": "Cell Door",
    "肩部": "Shoulders",
    "牢房": "Cell",
    "左手": "Left Hand",
    "右手": "Right Hand",
    "与": "and",
    "遗物宝箱": "Relic Chest",
    "地图画线损坏。": "Map path data is corrupted.",
    "皮带": "Belt",
    "%d层": "{p0} layer(s)",
    "受限": "Restricted",
    "升级时领取效果；当前等级详见出牌预览。": "Apply the upgrade effect; see the card preview for the current level.",
    "挣扎{base}。": "Struggle {p0}.",
    "牌": "card(s)",
    "开锁": "Unlock",
    "生命：%s\n": "HP: {p0}\n",
    "组合练习": "Combination Practice",
    "完成付款": "Complete Payment",
    "魅魔用手榨取了第一瓶精液": "The succubus milks out the first flask of semen by hand.",
    "你起身离开了牌桌。": "You rise and leave the card table.",
    "魅魔看见平板锁把肉棒压得一点也硬不起来，先是愣了愣，随即笑着从身后搂住你。双手揉压乳房、夹弄乳头，尾巴贴着小穴与阴蒂反复磨蹭；快感骤然冲上来，精液随高潮从锁具下流了出来": "The succubus notices the plate lock keeping your cock completely soft. She pauses in surprise, then smiles and wraps her arms around you from behind. She kneads your breasts and pinches your nipples while her tail rubs repeatedly against your pussy and clit. Arousal surges through you, and as you climax, semen leaks out beneath the lock.",
    "她没有停手，尾巴继续压着刚高潮过的阴蒂来回磨动，两根手指插进湿透的小穴连续勾弄，另一只手仍捏着乳头。第二次高潮很快压了上来，更多精液又从平板锁下断断续续流出": "She does not stop. Her tail keeps grinding over your still-sensitive clit while two fingers curl repeatedly inside your soaked pussy and her other hand continues pinching your nipple. A second climax quickly overwhelms you, and more semen trickles out from beneath the plate lock.",
    "切割": "Cut",
    "腿部": "Legs",
    "自由 · ": "Free · ",
    "打出「": "Play “",
    "强怪": "Strong Enemy",
    "一": "One",
    "二": "Two",
    "三": "Three",
    "所选卡牌已经不在卡组中。": "The selected card is no longer in your deck.",
    "，随后离场": ", then leaves",
    "执行收押": "Take Into Custody",
    "捕缚进度＋10": "Capture +10",
    "停顿": "Pause",
    "塔底入口": "Spire Entrance",
    "佩戴": "Equip",
    "施加了": "Applied ",
    "休息回合不足。": "Not enough rest turns.",
    "继续": "Continue",
    "取出": "Withdraw",
    "当前姿势下，": "In your current posture, ",
    "牢门已经打开。": "The cell door is already open.",
    "用": "Use ",
    "领取": "Claim",
    "前往": "Travel",
    "工具": "Tools",
    "道具": "Items",
    "监狱": "Prison",
    "塔路": "Spire Route",
    "手部": "Hands",
    "进入监狱": "Enter Prison",
    "诅咒平板锁": "Cursed Plate Lock",
    "支付%s魔力。": "Pay {p0} Mana.",
    "所选拘束具": "Selected Restraint",
    "装上": "Equip",
    "已经解除。": "Already removed.",
    "战斗遗物领取记录损坏。": "Battle relic claim data is corrupted.",
    "该敌人存活期间": "While this enemy is alive",
    "脚趾": "Toes",
    "%d张": "{p0} card(s)",
    "状态牌": "Status Card",
    "剩余%d回合": "{p0} turn(s) remaining",
    "战后整备": "Post-Battle Recovery",
    "下一次卡牌滑脱伤害×2。": "Next card Slip Damage ×2.",
    "滑脱{base}。": "Slip {p0}.",
    "挣扎{base}×{hits}。顺延。": "Struggle {p0} × {p1}. Delayed.",
    "状态": "Status",
    "魔力，不超过上限。": " Mana, up to the maximum.",
    "套体": "Sleeve",
    "般若汤赠牌": "Hannya Brew Card",
    "初级": "Basic",
    "中级": "Intermediate",
    "高级": "Advanced",
    "魔力商店": "Mana Shop",
    "战斗": "Battle",
    "金属与硅胶": "Metal and silicone",
    "夹在乳头上的无线震动夹。": "Wireless vibrating clamps worn on the nipples.",
    "环绕乳头持续震动。": "Vibrates continuously around the nipples.",
    "套在柱身上的震动环。": "A vibrating ring worn around the shaft.",
    "固定在冠沟位置的震动环。": "A vibrating ring fixed around the coronal ridge.",
    "你顶着新添拘束具的限制，终于勾住皮包的搭扣，将遗物抽了出来。她身上的拘束具仍原封不动。": "Working around the restraints newly added to your body, you finally hook the satchel clasp and pull out the relic. The restraints on her remain exactly as they were.",
    "魅魔低头看见平板锁把肉棒压得一点也硬不起来，明显怔了一下。“咦？连这里也锁住了呀？”她很快笑着从身后贴住你，揉压乳房、夹弄乳头，又用尾巴贴着小穴与阴蒂反复磨蹭，直到高潮将精液从锁具下流出": "The succubus looks down and pauses when she sees the plate lock keeping your cock completely soft. “Oh? They locked you up here too?” She soon presses against you from behind with a grin, kneading your breasts and pinching your nipples while her tail rubs over your pussy and clit, until you climax and semen leaks out beneath the lock.",
    "魅魔看着从锁具下流出的精液，笑着又敲了敲锁面。\n“姐姐连那根杂鱼肉棒都没碰哦？”\n“只是揉揉奶子、玩一下小穴，你就自己射出来了❤”\n\n她翻开牌面，啧了一声，把两枚心形筹码丢到桌上。\n“算你赢。筹码拿好啦。”": "The succubus watches the semen trickle out beneath the lock and taps its face with a teasing smile.\n“I didn't even touch that pathetic little cock, you know?”\n“All I did was fondle your tits and play with your pussy, and you came all by yourself❤”\n\nShe turns over the cards, clicks her tongue, and tosses two heart-shaped chips onto the table.\n“Fine, you win. Take your chips.”",
    "魅魔屈指敲了敲平板锁，低头看着锁具下面还在滴落的精液。\n“真的又射了呀？下面锁得这么严，奶子和小穴一碰却能连着射两次……”\n“你的杂鱼肉棒还真是不争气❤”\n\n她这才看向牌面。\n“这把也输了。都给你戴好，继续往上爬吧。”": "The succubus taps the plate lock with one finger and looks down at the semen still dripping beneath it.\n“You really came again? You're locked up so tightly down there, yet touching your tits and pussy made you come twice in a row…”\n“That pathetic little cock of yours really is hopeless❤”\n\nOnly then does she look at the cards.\n“I lost this hand too. I'll put everything on you, then you can keep climbing.”",
    "医用硅胶": "Medical silicone",
    "置于小穴内的无线跳蛋。": "A wireless egg vibrator placed inside the vagina.",
    "置于后庭内的无线跳蛋。": "A wireless egg vibrator placed inside the anus.",
    "由外部固定件压在小穴上的按摩棒。": "A vibrating wand held against the vagina by an external fixture.",
    "同时经过双穴区域，但只刺激小穴。": "Crosses both intimate areas but stimulates only the vagina.",
    " · %s魔力": " · {p0} Mana",
    "行动已失效，请重新选择。": "This action is no longer valid. Choose again.",
    "获得一件随机遗物。": "Gain a random relic.",
    "选择": "Select",
    "移除「{name}」": "Remove “{p0}”",
    "魅魔揉捏乳房与乳头，又用尾巴刺激小穴和阴蒂；锁下肉棒疯狂顶着锁板却无法勃起，精液随第一次高潮从平板锁下流出": "The succubus kneads your breasts and nipples while her tail stimulates your pussy and clit. Beneath the lock, your cock strains helplessly against the plate without becoming erect, and semen leaks out as your first climax hits.",
    "魅魔用乳沟榨取了第二瓶精液": "The succubus milks out the second flask of semen between her breasts.",
    "魅魔继续揉弄乳头，并用手指勾弄小穴；锁下肉棒再次徒劳顶动，更多精液随第二次高潮从平板锁下流出": "The succubus keeps teasing your nipples and curls her fingers inside your pussy. Your cock pushes helplessly against the lock again, and more semen leaks out beneath the plate lock with your second climax.",
    "就此离开": "Leave",
    "用1枚筹码换一张普通牌": "Trade 1 chip for a Common card",
    "的捕缚": "'s Capture",
    "消耗。": "Exhaust.",
    "固有。": "Innate.",
    "需要选择另一张当前手牌来消耗。": "Select another card in your hand to Exhaust.",
    "需要%s无拘束。": "Requires {p0} to be unrestrained.",
    "上身": "Upper Body",
    "超级顺延": "Full Follow-Through",
    "顺延": "Follow-Through",
    "的锁。": "'s lock.",
    "继续 · ": "Continue · ",
    "的": "'s ",
    "抽%d张%s": "Draw {p0} {p1}",
    "手指或脚趾任一部位自由即可使用。": "Requires either free fingers or free toes.",
    "show_pressure_sources 必须为布尔值。": "show_pressure_sources must be a boolean.",
    "show_pressure_sources 需要至少一个带 source 的快感效果。": "show_pressure_sources requires at least one Arousal effect with a source.",
    "同一个暂存 key 只能建立一次。": "The same temporary key can be created only once.",
    "选择一张牌": "Select a Card",
    "施加拘束具": "Apply Restraint",
    "施加复合拘束具": "Apply Composite Restraint",
    "展开六缚阵": "Deploy Sixfold Binding",
    "六重束装": "Sixfold Binding",
    "戏弄封缚": "Teasing Bind",
    "调教升温": "Heat Up",
    "复合束装": "Composite Binding",
    "六缚齐收": "Complete Sixfold Bind",
    "执行逮捕": "Make Arrest",
    "准备捕缚": "Prepare Capture",
    "发呆": "Idle",
    "甩缚": "Lashing Bind",
    "没有可以加固的拘束具，这次动作落空。": "There is no restraint to reinforce, so the action has no effect.",
    "本次没有指定要安装的装备。": "No equipment was selected for installation.",
    "装备品质或紧度档位不合法。": "The equipment quality or Tightness tier is invalid.",
    "本次不能替换刚安装的装备或附属件。": "Equipment or attachments installed during this action cannot be replaced.",
    "装备材质版本不合法。": "The equipment material version is invalid.",
    "该装备不能安装在这个位置。": "This equipment cannot be installed in that position.",
    "最外层没有满足本次容量、强度比较和完整覆盖要求的替换方案。": "No outermost replacement satisfies the capacity, strength, and full-coverage requirements.",
    "进入": "Enter",
    "你先行动": "You act first.",
    "敌人先行动": "The enemy acts first.",
    "单手套与拘束衣不能重复或互相覆盖。": "A single glove and a straitjacket cannot overlap or cover each other.",
    "所需位置已满。": "The required positions are full.",
    "翻卷收紧": "Wrap and Tighten",
    "准备捕缚。": "Prepare Capture.",
    "，紧度%d档。": ", Tightness tier {p0}.",
    "投降": "Surrender",
    "随身道具栏已满，无法拾取这件道具。": "Your inventory is full, so you cannot pick up this item.",
    "选择「": "Select “",
    "结束回合": "End Turn",
    "眼罩使站起额外消耗1能量。": "The blindfold makes standing up cost 1 additional Energy.",
    "打断": "Interrupt",
    "；可用部位：": "; available body parts: ",
    "安装到": "Install on ",
    "行动未提交：": "Action not submitted: ",
    "：本次施法必定成功。": ": This cast is guaranteed to succeed.",
    "，剩余耐久": ", remaining Durability ",
    "，收入道具栏。": ", added to your inventory.",
    "请先使用或放下超出容量的随身道具。": "Use or drop the items exceeding your inventory capacity first.",
    "当前房间还有未完成的事项，不能离开。": "You cannot leave while something in this room remains unresolved.",
    "无法继续这份存档：": "Unable to continue this save: ",
    "%s · 可使用%d次": "{p0} · {p1} use(s)",
    " · 领取后收入道具栏": " · Added to inventory when claimed",
    "选择一张卡牌": "Select a Card",
    "加入你的卡组": "Add to your deck",
    "已获得「": "Already gained “",
    "战 斗 奖 励": "Battle Rewards",
    "继续  ›": "Continue  ›",
    "位置：": "Position: ",
    "锁已打开": "Lock Open",
    "触手固定": "Tentacle Bind",
    "足部": "Feet",
    "需要先靠到工具所在墙边。": "Move beside the wall-mounted tool first.",
    "存入": "Deposit",
    "滑精": "Leaking Climax",
    "本回合深呼吸次数不正确。": "The Deep Breath count for this turn is invalid.",
    "普通或复合": "Standard or Composite",
    "高安全监室": "High-Security Cell",
    "需要先到通风口前。": "Move in front of the vent first.",
    "闪避抵消了%d件。": "Evasion prevented {p0} item(s).",
    "床边": "Bedside",
    "靠墙": "Against the Wall",
    "已经在这里。": "You are already here.",
    "引敌缚咒": "Binding Lure",
    "已经拥有这件遗物。": "You already own this relic.",
    "持有%d件。": "Holding {p0} item(s).",
    "战斗结束": "Battle Over",
    "恢复%s魔力。": "Restore {p0} Mana.",
    "魔力耳坠": "Mana Earrings",
    "事件道具奖励记录不完整。": "Event item reward data is incomplete.",
    "解除了": "Removed ",
    "恢复%s魔力，当前魔力%s/%s。": "Restore {p0} Mana. Current Mana: {p1}/{p2}.",
    "贴身魔瓶获得%s魔力，当前储量%s。": "The flask gains {p0} Mana. Current reserve: {p1}.",
    "诅咒眼罩无法解除。": "The cursed blindfold cannot be removed.",
    "已经松到%d档。": "Already loosened to tier {p0}.",
    "事件仍有尚未归还的装备。": "The event still has equipment that has not been returned.",
    "事件战斗记录不完整。": "Event battle data is incomplete.",
    "魔力恢复至%s/%s。": "Mana restored to {p0}/{p1}.",
    "事件道具奖励混入了战斗奖励记录。": "Event item rewards were mixed into the battle reward data.",
    "事件阶段不合法。": "The event stage is invalid.",
    "进入商店": "Enter Shop",
    "店主": "Shopkeeper",
    "存档小数损坏。": "A decimal value in the save is corrupted.",
    "存档数值损坏。": "A numeric value in the save is corrupted.",
    "尚无存档。": "No save data found.",
    "存档位置不存在。": "The save location does not exist.",
    "左肩": "Left Shoulder",
    "右肩": "Right Shoulder",
    "绳": "Rope",
    "房间敌人组合不符合生成要求。": "The room's enemy group does not meet the generation requirements.",
    "房间缺少指定种类的敌人。": "The room is missing the required enemy type.",
    "房间敌人池损坏。": "The room enemy pool is corrupted.",
    "敌人行动历史损坏。": "Enemy action history is corrupted.",
    "事件暂存装备记录损坏。": "Event equipment storage data is corrupted.",
    "本玩家回合结束后解除": "Removed at the end of this player turn",
    "%d件": "{p0} item(s)",
    "手部辅助": "Hand Assistance",
    "环境": "Environment",
    "狱警巡视": "Guard Patrol",
    "连接式固缚耐久不正确。": "Connected restraint Durability is invalid.",
    "手指": "Fingers",
    "汇流": "Confluence",
    "每佩戴{bound_worn_divisor}件拘束具，本回合获得1点力量，不足{bound_worn_divisor}件不计。{bound_worn_preview}": "For every {p0} restraints worn, gain 1 Strength this turn; fewer than {p1} grant nothing.{p2}",
    "每佩戴{free_worn_divisor}件拘束具，恢复1点魔力。{free_worn_preview}": "For every {p0} restraints worn, restore 1 Mana.{p1}",
    "按打出时的当前佩戴件数计算；复合拘束具整件计1件。力量可通过重复使用叠加，回合结束消失。": "Count restraints when this card is played; a composite restraint counts as one item. Strength gained from repeated uses stacks and expires at the end of the turn.",
    "\n当前：恢复%s魔力。": "\nCurrent: Restore {p0} Mana.",
    "\n当前：本回合力量＋%s。": "\nCurrent: Strength +{p0} this turn.",
    "拘束": "Bound",
    "转换": "Conversion",
    "再利用": "Reuse",
    "共鸣": "Resonance",
    "熟练而已": "Practiced",
    "汲取力量": "Siphon Strength",
    "命运同担": "Shared Fate",
    "借力打力": "Leverage",
    "运气": "Breath Control",
    "紧缚爱好": "Binding Enthusiast",
    "灌注": "Infusion",
    "专心致志": "Concentration",
    "魔力回路": "Mana Circuit",
    "蓄势待发": "Ready to Strike",
    "翘腿无视": "Crossed Legs",
    "魔路检索": "Mana Search",
    "强欲之壶": "Pot of Greed",
    "连续挣": "Repeated Strain",
    "余势复演": "Echo Cast",
    "余火": "Embers",
    "猛火下山": "Wildfire Descent",
    "猪神之皇焚": "Boar Emperor Blaze",
    "灵活变通": "Adaptability",
    "死灰复燃": "Rekindle",
    "火动力学": "Fire Dynamics",
    "炫火": "Flame Flourish",
    "控火": "Fire Control",
    "开信刀play": "Letter Opener Play",
    "欲能转换": "Arousal Conversion",
    "魔力转换": "Mana Conversion",
    "魔力涌流": "Mana Surge",
    "火焰精通": "Fire Mastery",
    "找准松处": "Find the Weak Spot",
    "扯开缺口": "Tear It Open",
    "接连挣动": "Chain Struggle",
    "逐层抽离": "Peel Away",
    "双重解锁": "Double Unlock",
    "慌乱": "Panic",
    "敏感": "Sensitive",
    "玩弄": "Tease",
    "玩弄+": "Tease+",
    "绷紧再挣": "Brace and Strain",
    "一点点抽出": "Inch Free",
    "魔力松缚": "Mana Slip",
    "将快感与魔力均设为两者总和的一半。": "Set both Arousal and Mana to half their combined total.",
    "{mana_cost}每使用火球术：抽牌1。": "{p0}Whenever you use Fireball: Draw 1 card.",
    "可叠加。失败火球也触发；群攻每层触发一次。": "Stackable. Failed Fireballs also trigger it; area attacks trigger once per stack.",
    "火球现在可以对拘束具使用,但是伤害减半": "Fireball can now target restraints, but deals half damage.",
    "每回合火球次数＋1。": "+1 Fireball use each turn.",
    "自由面次数可叠加，拘束面不叠加。敌人与拘束具共用次数。": "Extra uses from the Free face stack; the Bound face does not. Enemies and restraints share the same use limit.",
    "删牌服务 · %s魔力": "Card Removal · {p0} Mana",
    "火球无视身体限制；不获得手势加成。": "Fireball ignores body restrictions and gains no gesture bonus.",
    "火球伤害×2。": "Fireball Damage ×2.",
    "同面不叠加；费用与快感施法概率不变。": "The same face does not stack. Cost and Arousal-based cast chance remain unchanged.",
    '保留全部手牌': 'Retain all cards in hand',
    '全部保留不能同时指定选牌数量。': 'Retain all cannot also specify a selection count.',
    '本回合结束时，保留的手牌不会丢弃。': 'Retained cards are not discarded at the end of this turn.',
    '带着一个%s点生命的玩偶登场。': 'enters with a puppet with {p0} HP.',
    '生命：%s\n开场：自带10生命玩偶。首回合赋予玩偶嘲讽与受伤反击。\n行动：玩偶生命上限＋5并回满→准备中级2档复合拘束具→准备中级3档特殊装备，循环。两类装备各保留1件，同类新准备替换旧准备。\n牵线保护：玩偶生命最低为1，溢出伤害全额转给玩偶师。击败玩偶师，玩偶同时消失。': 'HP: {p0}\nStarts with a 10-HP puppet. Turn 1: Grant the puppet Taunt and a reaction that applies a restraint when damaged.\nThen repeat: Raise puppet max HP by 5 and fully heal it; prepare a medium tier-2 composite restraint; prepare medium tier-3 special equipment. Each equipment category holds one prepared item; a new preparation replaces the old one.\nThe puppet cannot fall below 1 HP and transfers excess damage to its puppeteer. Multi-hit attacks trigger the reaction per hit. Area attacks ignore Taunt. Defeating the puppeteer dismisses the puppet; rewards are granted once.',
    "预备咏唱": "Prepared Chant",
    "本回合施法成功率固定为100%。": "Cast success rate is fixed at 100% this turn.",
    "{mana_cost}本回合施法成功率固定为100%。": "{p0}Cast success rate is fixed at 100% this turn.",
    "：施法成功率固定为100%。": ": Cast success rate is fixed at 100%.",
    "问题与建议": "Issues and Suggestions",
    "每使用火球术：抽牌1。": "Whenever you use Fireball, draw 1 card.",
    "火球术施法成功率＋30%。": "Fireball cast success rate +30%.",
    "唯一": "Unique",
    "回廊": "Corridor", "开": "On", "关": "Off", "扶她出去": "Futa Off",
    "次": " time(s)", "层": " stack(s)", "已经降到最低": "Already at minimum",
    "用力": "Strain", "用力！": "Strain!", "顾涌": "Wriggle", "顾涌！": "Wriggle!", "术式解锁": "Spell Unlock",
    "蓄力": "Charge", "闪避": "Evasion", "力量": "Strength", "灵巧": "Dexterity",
    "快感": "Arousal", "魔力": "Mana", "能量": "Energy", "耐久": "Durability",
    "紧度": "Tightness", "挣扎": "Struggle", "滑脱": "Slip", "伤害": "Damage",
    "拘束具": "Restraint", "施法": "Cast", "卡组": "Deck", "手牌": "Hand", "卡牌": "Card",
    "普通": "Common", "罕见": "Uncommon", "稀有": "Rare", "成功": "Success", "失败": "Failure",
    "回合开始": "Start of Turn", "回合结束": "End of Turn",
    "魔力撑隙": "Mana Expansion", "汲取": "Siphon", "激发魔力": "Mana Surge",
    "拘束之拥": "Restraint's Embrace", "魔术手": "Mage Hand", "身轻如燕": "Featherlight",
    "需要双腿活动": "Requires free leg movement", "解除": "Remove",
    "打出时播放": "Play on use: ", "版雨爱": "Rain Love Remix", "品相完美": "Pristine",
    "般若汤": "Hannya Brew", "其二": "Part Two", "受": "Affected", "需要": "Requires",
    "扶她出去 · ": "Futa Off · ", "贞操锁池": "Chastity Lock Pool",
    "贞操锁池 · %s（%d%%）": "Chastity Lock Pool · {p0} ({p1}%)",
    "开启贞操锁池后可选": "Available after enabling the Chastity Lock Pool",
    "仅新局生效 · 勾选后不出现第4项开局选项": "New games only · Hides the fourth starting choice",
    "月灯杂货铺": "Moonlight General Store", "拘束具堆里的微光": "A Glimmer in the Restraint Pile",
    "全量蓄力": "Full Charge", "普通蓄力": "Normal Charge", "切换为全量蓄力": "Switch to Full Charge",
    "切换为普通蓄力": "Switch to Normal Charge", "敌人正在蓄力": "Enemy is charging",
    "敌人正在蓄力。": "The enemy is charging.", "本回合正在高潮": "Climaxing this turn",
    "获得%d层蓄力": "Gain {p0} Charge", "获得%d层蓄力。": "Gain {p0} Charge.",
    "火球术 · 自解": "Fireball · Self-Release", "贴身刺激与高潮练习": "Intimate Stimulation & Climax Practice",
    "每耗魔20：蓄力1。": "For every 20 Mana spent: Gain 1 Charge.",
    "继续 · 高潮后缓一缓": "Continue · Recover after climax",
    "高潮 · 先缓过这一回合": "Climax · Recover for this turn",
    "高潮练习": "Climax Practice", "下次火球术：复放1。": "Next Fireball: Replay once.",
    "下一次触发使用全部蓄力。": "The next trigger consumes all Charge.",
    "本回合火球术次数已用完。": "No Fireball uses remain this turn.",
    "高潮打断了剩余卡牌效果。": "Climax interrupted the remaining card effects.",
    "入口回廊": "Entrance Corridor", "中央回廊": "Central Corridor", "左侧回廊": "Left Corridor", "右侧回廊": "Right Corridor",
    "偏左回廊": "Left-Center Corridor", "偏右回廊": "Right-Center Corridor",
    "最左回廊": "Far-Left Corridor", "最右回廊": "Far-Right Corridor",
    "身体与拘束具": "Body & Restraints", "颈肩": "Neck & Shoulders", "大臂": "Upper Arms",
    "小臂": "Forearms", "双穴": "Vagina & Anus", "眼部": "Eyes", "口部": "Mouth",
    "乳头": "Nipples", "肉棒": "Penis", "大腿": "Thighs", "小腿": "Calves", "脚踝": "Ankles",
    "脚掌": "Feet", "施法：": "Casting: ", "无": "None", "技能": "Skill", "魔法": "Spell",
    "能力": "Power", "基础": "Basic", "保留": "Retain", "保留。": "Retain.", " · 保留": " · Retain",
    "第%d层": "Floor {p0}", "第0层": "Floor 0", "第%d回合": "Turn {p0}", "非战斗": "Out of Combat",
    "回合 —": "Turn —", "教程书": "Tutorial",
    "距墙%d格": "{p0} tiles from wall", "离墙%d格": "{p0} tiles from wall", "警戒度%d级": "Alert {p0}",
    "道具 %d / %d": "Items {p0}/{p1}", "能力区 · %d": "Powers · {p0}",
    "近身短打": "Close Strike", "近身短打 · 连击": "Close Strike · Combo", "肘击": "Elbow Strike",
    "强力肘击": "Heavy Elbow", "深呼吸": "Deep Breath", "并腿飞踢": "Flying Kick",
    "并拢飞踢": "Flying Kick", "坐姿踢击": "Seated Kick", "站着踢": "Standing Kick", "横扫": "Sweep",
    "当前快感已经降到最低": "Arousal is already at its minimum", "当前快感已经降到最低。": "Arousal is already at its minimum.",
    "魔力药剂": "Mana Potion", "活力药剂": "Energy Potion", "蓄势药剂": "Charge Potion",
    "应变卷轴": "Tactical Scroll", "节魔卷轴": "Mana-Saving Scroll", "定咒卷轴": "Surecast Scroll",
    "便携开锁针": "Lockpick Set", "润滑油": "Lubricant", "冰心诀": "Heart of Ice",
    "断缚护腕": "Sunder Bracers", "小刻印": "Minor Sigil", "拘束解除": "Remove Restraints",
    "删牌服务 · 本店一次": "Card Removal · Once per Visit",
    "删牌服务 · 已使用": "Card Removal · Used", "整理道具": "Manage Items", "继续旅程 →": "Continue Journey →",
    "自身魔力 ": "Personal Mana ", "魔瓶魔力 ": "Flask Mana ",
    "漂浮绳索": "Floating Rope", "漂浮胶带": "Floating Tape", "漂浮皮带": "Floating Belt",
    "漂浮皮带群": "Floating Belt Cluster", "【迎战】打散皮带群": "[Fight] Break Up the Belt Cluster",
    "【硬闯】把挡路的皮带打散": "[Fight] Break Through the Belt Cluster",
    "与3只初级漂浮皮带战斗；胜利后获得稀有遗物「软化扣环」。": "Fight three lesser Floating Belts; victory grants the rare relic “Softened Buckle.”",
    "【接受灌注】走进皮带群中": "[Accept Infusion] Enter the Belt Cluster",
    "恢复25魔力；获得诅咒「淫纹」。": "Restore 25 Mana; gain the curse “Lewd Mark.”",
    "走廊前方传来一阵密集的金属轻响。\n\n十几条漂浮皮带挤在一起，宽大的带身盘成一圈圈，几乎封死了整条路。皮带扣不断开合，像是在等什么东西主动靠近。\n\n其中几条皮带内侧浮动着粉色的魔力，甜腻的气息隔着一段距离都能感觉到。": "A rapid metallic clatter echoes from the corridor ahead.\n\nMore than a dozen floating belts crowd together, their broad straps coiling into rings that nearly block the passage. Their buckles snap open and shut as if waiting for something to come closer.\n\nPink mana shimmers along the inner faces of several belts, carrying a cloyingly sweet scent even at a distance.",
    "可以迎战三只初级漂浮皮带并取得稀有遗物「软化扣环」，或接受魔力灌注，恢复25魔力并获得诅咒「淫纹」。": "Fight three lesser Floating Belts to claim the rare relic “Softened Buckle,” or accept a mana infusion to restore 25 Mana and gain the curse “Lewd Mark.”",
    "“欢迎光临呀，zako♡”\n\n“本店不收金币，只收含着魔力的精液。实在不想当场射，用魔瓶里的存货也行。”\n\n“喜欢什么就自己挑吧，付不起可别盯着看太久哦♡”": "“Welcome, zako♡”\n\n“We don't take coins here—only semen infused with mana. If you really don't want to cum on the spot, you can use what's stored in your flask.”\n\n“Pick anything you like. Just don't stare too long if you can't afford it♡”",
    "“用魔瓶付？真没劲。”\n\n“人家还以为能看看你当场射出来的样子呢。”\n\n“商品拿去啦。下次记得用肉棒亲自结账♡”": "“Paying with the flask? Boring.”\n\n“I thought I'd get to watch you cum right here.”\n\n“Fine, take it. Next time, remember to pay with your cock in person♡”",
    "henshin（品相完美!）": "Henshin (Pristine!)", "般若汤-其一": "Hannya Brew · Part One",
    "般若汤-其二": "Hannya Brew · Part Two", "般若汤-其三": "Hannya Brew · Part Three",
    "般若汤-其四": "Hannya Brew · Part Four", "好汤喝够饮饮饮饮": "Drink Your Fill",
}

# Human-reviewed English for runtime copy added or rewritten during v0.17.
# Keep these overrides after the broader transitional table so rebuilding the
# compatibility catalog cannot restore an earlier machine-generated draft.
MANUAL.update({
    "魔力预备": "Mana Reserve",
    "获得%d层魔力预备": "Gain {p0} Mana Reserve",
    "回合开始：获得1层魔力预备。": "At turn start: gain 1 Mana Reserve.",
    "\n失败返还本次耗魔的50%，能量照扣。": "\nFailed casts refund 50% of the Mana spent; Energy is still spent.",
    "\n脚趾施法成功率×0%；解除脚趾拘束后停止。": "\nToe casting success rate ×0% while the toes are bound; ends when the toe restraints are removed.",
    "\n普通单件仅有向下链接时，普通／魔法滑脱伤害×1.25；多条向下链接不重复加成。链接自身不吃此加成，任一必要端解除时一并移除。": "\nAn ordinary restraint with only downward links takes ×1.25 damage from normal or magic Slip; multiple downward links do not stack this bonus. The links themselves receive no bonus and are removed when either required end is released.",
    "蓄力保留，精神集中失去1层。": "Spell Preparation is retained; lose 1 Mental Focus.",
    "当前X＝%d：%s随后恢复%d自身魔力。": "Current X = {p0}: {p1}, then restore {p2} personal Mana.",
    "没有拘束具可供火球术选为目标。": "No restraint is available as a Fireball target.",
    "能力牌的本回合失败记录损坏。": "Invalid failed-cast record for this power this turn.",
    "角色2不使用这些开局选项": "Character 2 does not use these starting options",
    "切换至快捷挣脱栏": "Switch to Quick Release Bar",
    "双臂受限达到三级": "Arm restraint level 3",
    "腿部严密度达到4级": "Leg restraint level 4",
    "魔路精通·拘束": "Mana Circuit Mastery · Bound",
    "魔路精通·自由": "Mana Circuit Mastery · Free",
    "自由：": "Free:",
    "嘴部": "Mouth",
    "获得3能量、8层魔力预备和3层精神集中，清空快感。本回合快感获取量×0.5。": "Gain 3 Energy, 8 Mana Reserve, and 3 Mental Focus. Clear Arousal. Arousal gain ×0.5 this turn.",
    "：获得%d层魔力预备。": ": Gain {p0} Mana Reserve.",
    "回合开始时，获得2层魔力预备。可叠加。": "At turn start, gain 2 Mana Reserve. Stacks.",
    "战斗中每回合开始时，获得1层魔力预备。": "At the start of each combat turn, gain 1 Mana Reserve.",
    "每个部位每回合预备次数不限，只能成功释放1次。点击使用，右键切换施法预备／释放；也可拖到敌人身上。\n四部位施法预备均消耗1能量、5魔力。火焰箭：1能量5魔力，6伤；吹雪：2能量10魔力，全体4伤；思维侵入：1能量5魔力，4伤。每层施法预备额外造成一段伤害，成功释放消耗对应部位全部施法预备。\n腿部施法预备至少4层可用魔女飞踹：1能量、1伤害、打断，消耗全部腿部施法预备。各动作按对应部位判定成功率；失败保留施法预备，精神集中失去1层。\n精神集中每层使下一次伤害魔法各段＋1，整次用完。对应身体部位将被拘束时，2层施法预备可抵挡1次；高潮清空四部位施法预备并失去1层精神集中。精神集中跨战斗最多保留2层，乌龟壳提高至4层。释放后动作自动切回施法预备。初始魔力与快感上限75，魔瓶50魔力；魔女护符在战斗每回合开始时获得1层魔力预备。": "Each body part can prepare any number of times per turn, but can successfully release only once. Click to use; right-click to switch between Spell Preparation and Release. You can also drag the action onto an enemy.\nPreparing any of the four parts costs 1 Energy and 5 Mana. Fire Arrow costs 1 Energy and 5 Mana for 6 damage; Flurry costs 2 Energy and 10 Mana for 4 damage to all enemies; Mind Intrusion costs 1 Energy and 5 Mana for 4 damage. Each Spell Preparation stack adds one hit, and a successful release consumes all preparation on that part.\nWith at least 4 Leg Spell Preparation, Witch Kick costs 1 Energy, deals 1 damage, and interrupts; it consumes all Leg Spell Preparation. Each action checks casting success for its corresponding body part. Failure preserves Spell Preparation and removes 1 Mental Focus.\nEach Mental Focus adds 1 damage to every hit of the next damaging spell, then all stacks are consumed. When a restraint would be applied to the matching body part, 2 Spell Preparation can block it once. A climax clears Spell Preparation from all four parts and removes 1 Mental Focus. Retain up to 2 Mental Focus between battles, or 4 with Turtle Shell. After a release, the action automatically switches back to Spell Preparation. Maximum Mana and Arousal begin at 75; the Mana Flask begins with 50 Mana. Witch Amulet grants 1 Mana Reserve at the start of each combat turn.",
    "开场：手腕、口部、脚踝各施加1件中级2档拘束具；准备1回合后施加捕缚50/100。无法新增或合法替换时，改为加固该处1次；紧度3且可上锁时，上锁并恢复满耐久。\n行动：中级2档普通拘束具×2→捕缚＋10→中级2档复合拘束具×1，循环。复合无法施加时，改为加固至多2件至3档。\n捕缚效果：上身束缚等级至少1；姿态只能躺姿→坐姿→站姿，每次切换捕缚＋10。每次花费能量，使一个随机特殊部位增加10点基础快感（受敏感度影响）；每次高潮捕缚＋10。": "Opening: Apply one medium tier-2 restraint each to the wrists, mouth, and ankles. After 1 turn of preparation, apply 50/100 Capture. If no new or legal replacement restraint fits a slot, reinforce that slot once; at tightness 3, lock a lockable restraint and restore it to full durability.\nActions: Cycle through two medium tier-2 ordinary restraints → Capture +10 → one medium tier-2 composite restraint. If the composite cannot be applied, reinforce up to two restraints to tier 3 instead.\nCapture: Upper-body restraint level counts as at least 1. Posture can only advance lying → sitting → standing, and each change adds 10 Capture. Each Energy spent adds 10 base Arousal to a random intimate area (modified by sensitivity); each climax adds 10 Capture.",
    "解除捕缚：挣扎／滑脱牌可削减进度，不含环境加成；仅有眼罩、口球或没有拘束具时伤害×2。归零后解除，敌人会准备1回合再施加。\n捕缚规则：被捕缚时无法移动，先解除捕缚。同种不叠加；异种共用进度，新种只增加其初始值的一半。达到100后，施加捕缚的敌人在下次行动收押。击败来源解除对应效果，全部来源离场则清空进度。": "Breaking Capture: Struggle and Slip cards reduce progress without environmental bonuses; damage is doubled when only blindfolds or gags—or no restraints—remain. At 0, Capture ends; the enemy prepares for 1 turn before applying it again.\nCapture rules: You cannot move while Captured. Capture of the same type does not stack; different types share progress, and a new type adds half its starting value. At 100, the enemy that applied Capture imprisons you on its next action. Defeating a source removes its effect; progress is cleared when all sources leave.",
    "被捕缚时无法移动，先解除捕缚。挣扎／滑脱牌可直接削减进度；除眼罩、口球外没有其他拘束具时伤害翻倍，不受环境加成。上身受限至少按1级计算。同种捕缚不叠加；新种类增加其初始值的一半。降至0全部解除，达到100后下一敌方回合执行收押。": "You cannot move while Captured; break free first. Struggle and Slip cards reduce Capture directly. Damage is doubled when no restraints remain except blindfolds and gags, and environmental bonuses do not apply. Upper-body restraint level counts as at least 1. Capture of the same type does not stack; a new type adds half its starting value. At 0, all Capture ends; at 100, you are imprisoned on the next enemy turn.",
    "肩带剩2条：套体不能滑脱；剩1条：滑脱效果×0.5；全解除：恢复原效果。任意肩带解除后，套体非3档且无外层阻挡，再次挣扎可直接脱下。\n肩带左右独立；达到3档后交叉禁滑脱，降至1档才解除此封锁。套体破坏后肩带一并解除。": "Two shoulder straps block slipping off the sleeve; one remaining strap multiplies Slip by 0.5; removing both restores the normal effect. Once either strap is removed, another Struggle can pull off the sleeve if it is below tightness tier 3 and has no outer obstruction.\nThe left and right straps are independent. At tier 3, a crossed strap blocks Slip until reduced to tier 1. Destroying the sleeve also removes both straps.",
    "开场会束住手腕、口部和脚踝，再准备并施加50/100的捕缚。无法新增或合法替换时，改为加固该处1次；紧度3且可上锁时，上锁并恢复满耐久。用挣扎或滑脱牌削减捕缚；达到100后，警卫下一次行动会收押你。": "At the start, the guard restrains your wrists, mouth, and ankles, then prepares and applies 50/100 Capture. If no new or legal replacement restraint fits a slot, that slot is reinforced once; at tightness 3, a lockable restraint is locked and restored to full durability. Use Struggle or Slip cards to reduce Capture. At 100, the guard imprisons you on its next action.",
    "战斗初始距墙1—4格；休息房和牢房从墙边开始。\n“向墙移动”每次1—2格、消耗1—3能量，按姿态和行动能力决定。到墙后获得“贴墙”，移动不自动结束回合。被捕缚时无法移动，先解除捕缚。": "Combat begins 1–4 spaces from the wall; rest rooms and prison cells begin beside it.\nMove Toward Wall travels 1–2 spaces and costs 1–3 Energy depending on posture and mobility. Reaching the wall grants Against Wall; moving does not automatically end the turn. You cannot move while Captured, so break free first.",
    "普通单件仅有向下链接时，普通／魔法滑脱伤害×1.25；多条向下链接不重复加成。链接自身不吃此加成，任一必要端解除时一并移除。": "An ordinary restraint with only downward links takes ×1.25 damage from normal or magic Slip; multiple downward links do not stack this bonus. The links themselves receive no bonus and are removed when either required end is released.",
    "下次造成伤害的魔法每段伤害增加对应层数，整次施放消耗全部层数。施法失败或高潮时失去1层。跨战斗最多保留2层，乌龟壳提高至4层。": "Each hit of your next damaging spell gains damage equal to your Mental Focus stacks; the full cast consumes all stacks. Lose 1 stack on a failed cast or climax. Retain up to 2 stacks between battles, or 4 with Turtle Shell.",
    "持有监门钥匙或正在反抗时暂停巡视。拘束具或性玩具缺件会分别触发补装；每次完整检查最后补满性玩具电池。\n": "Patrols pause while you hold the cell key or are resisting. Missing restraints and sex toys are replaced separately; every completed inspection fully recharges all sex toys.\n",
    "下2次手部基础动作忽略拘束条件。每次完整动作消耗1次，次数可累计；仍判定施法成功率。": "The next 2 hand-based basic actions ignore restraint conditions. Each completed action consumes 1 use; uses can stack. Casting success is still checked.",
    "下次造成伤害的魔法每段伤害＋%d，整次施放消耗全部层数。施法失败或高潮时失去1层。": "Each hit of your next damaging spell gains +{p0} damage; the full cast consumes all stacks. Lose 1 stack on a failed cast or climax.",
    "切换至快捷挣脱栏，可对选中的拘束具使用解除牌，也可使用已安装道具。": "Switch to the Quick Release Bar. Use release cards on the selected restraint, or use an installed tool.",
    "每有1点魔力，造成的伤害提高1%。计入自身与临时魔力，可叠加。": "Gain +1% damage for each point of Mana. Both personal and Temporary Mana count; multiple copies stack.",
    "先选部位再点牌，或直接拖牌；右键切小部位，左右箭头切换拘束具。": "Select a body area, then click a card—or drag the card directly. Right-click to switch precise locations; use the left and right arrows to switch restraints.",
    "对应部位被施加拘束时可消耗2层抵挡；不足2层不能抵挡。": "When a restraint would be applied to the matching body part, spend 2 Spell Preparation to block it. Fewer than 2 stacks cannot block it.",
    "每累计消耗20魔力，精神集中1。计入临时魔力，可叠加。": "Gain 1 Mental Focus for every 20 Mana spent in total. Temporary Mana counts; multiple copies stack.",
    "无需手部或嘴部动作，仍受快感及施法成功率加成影响。": "Requires no hand or mouth action. Arousal and casting-success bonuses still apply.",
    "失去初始遗物「%s」，获得1件随机Boss遗物。": "Lose the starting relic “{p0}” and gain 1 random Boss relic.",
    "\n秘密武器：手部%s，脚趾%s，取较高成功率。": "\nSecret Weapon: hands {p0}; toes {p1}. Use the higher casting success rate.",
    "脚趾施法成功率×0%；解除脚趾拘束后停止。": "Toe casting success rate ×0% while the toes are bound; ends when the toe restraints are removed.",
    "每次消耗能量时触发一次；额外牵扯也会触发。\n": "Triggers once whenever Energy is spent; additional traction also triggers it.\n",
    "本次各段魔法伤害＋%d，消耗全部精神集中。": "Each hit of this spell gains +{p0} damage; consume all Mental Focus.",
    "牌面消耗需要技能或魔法自身效果的布尔配置。": "Card-face consumption must be configured as a boolean on the skill or spell itself.",
    "失败返还本次耗魔的50%，能量照扣。": "Failed casts refund 50% of the Mana spent; Energy is still spent.",
    "回合开始时，获得2层魔力预备。可叠加。": "At turn start, gain 2 Mana Preparation. Stacks.",
    "失败转换的返还、能量或次数配置不正确。": "Invalid failed-cast conversion refund, Energy, or trigger-count configuration.",
    "战斗中每回合开始时，获得1层魔力预备。": "At the start of each combat turn, gain 1 Mana Preparation.",
    "若持续无法行动，也可以投降进入牢房。": "If you remain unable to act, you can also surrender and be sent to prison.",
    "该角色没有这件装备所需的身体部位。": "This character does not have the body parts required by this equipment.",
    "该遗物提供的卡牌不适用于当前角色。": "The card granted by this relic is not compatible with the current character.",
    "尚未获得用火球术解除拘束具的能力。": "You have not unlocked the ability to use Fireball on restraints.",
    "{mana_cost}能量＋2。": "{p0} Energy + 2.",
    "成功率受快感和腿部受限等级影响。": "Success rate is affected by Arousal and leg restraint level.",
    "该角色没有此遗物所需的身体部位。": "This character does not have the body parts required by this relic.",
    "回合开始时，精神集中1。可叠加。": "At turn start, gain 1 Mental Focus. Stacks.",
    "使用后清除；跨战斗最多保留%d层": "Cleared after use; retain up to {p0} stacks between battles",
    "。次数用完后恢复普通50%返还": ". Once the trigger limit is reached, return to the normal 50% refund",
    "卡组中含有其他角色的专属卡牌。": "The deck contains a character-exclusive card belonging to another character.",
    "临时魔力付款条件需要布尔配置。": "The Temporary Mana payment condition must be configured as a boolean.",
    "下2次手部基础动作忽略拘束条件": "The next 2 hand-based basic actions ignore restraint conditions",
    "下次基础动作费用－2，最低0。": "Next basic action costs 2 less, to a minimum of 0.",
    "战斗开始时，获得2层精神集中。": "At combat start, gain 2 Mental Focus.",
    "这张牌不能用于当前选中的拘束具": "This card cannot be used on the selected restraint",
    "互斥能力需要有效的互斥组。": "Mutually exclusive powers require a valid exclusion group.",
    "已经失去初始遗物「%s」。": "You have already lost the starting relic “{p0}”.",
    "%s伤害%s×%d。%s": "{p0} damage {p1} × {p2}. {p3}",
    "本场整备结束或高潮时清空": "Cleared when this encounter's preparation ends or upon climax",
    "该遗物不适用于当前角色。": "This relic is not compatible with the current character.",
    "角色2 · 固定站立立绘": "Character 2 · Fixed Standing Portrait",
    "收押装备文案记录不完整。": "Incomplete intake-equipment copy record.",
    "：获得%d层魔力预备。": ": Gain {p0} Mana Preparation.",
    "每15快感获得1能量。": "Gain 1 Energy for every 15 Arousal.",
    "部位蓄力层数不正确。": "Invalid per-part Spell Preparation stack count.",
    "部位蓄力记录不完整。": "Incomplete per-part Spell Preparation record.",
    "精神集中层数不正确。": "Invalid Mental Focus stack count.",
    "卡牌消耗记录不正确。": "Invalid card-consumption record.",
    "收押演出记录不完整。": "Incomplete intake-scene record.",
    "\n消耗%d能量。\n": "\nSpend {p0} Energy.\n",
    "：精神集中－%d。": ": Mental Focus −{p0}.",
    "：精神集中＋%d。": ": Mental Focus +{p0}.",
    "魔力回路·精神集中": "Mana Circuit · Mental Focus",
    "上一个拘束具（←）": "Previous Restraint (←)",
    "下一个拘束具（→）": "Next Restraint (→)",
    "角色记录不正确。": "Invalid character record.",
    "进入高安全监室。": "Enter the high-security cell.",
    "装备记录不正确。": "Invalid equipment record.",
    "×  处罚执行": "×  Penalty Applied",
    "×  发现问题": "×  Problem Found",
    "◇  巡视开始": "◇  Patrol Begins",
    "✓  登记无误": "✓  Registration Confirmed",
    "✓  检查通过": "✓  Inspection Passed",
    "的动作被打断。": "'s action was interrupted.",
    "小魔女·测试版": "Little Witch · Test Build",
    "精神集中%d": "Mental Focus {p0}",
    "辣椒炒肉拌面": "Spicy Pork Noodles",
    "Boss奖励": "Boss Reward",
    " · 解缚": " · Release",
    "当前%d层": "Current: {p0} stacks",
    "卡牌／遗物": "Cards / Relics",
    "没有拘束具": "No restraints",
    "魔女飞踹！": "Witch Kick!",
    "，顺延。": ", follow through.",
    "部位 ×": "Position ×",
    "道具使用": "Use Item",
    "堆叠 ×": "Stacking ×",
    "精神集中": "Mental Focus",
    "精神施法": "Mind Casting",
    "魔法钥匙": "Magic Key",
    "魔力积蓄": "Mana Accumulation",
    "魔女护符": "Witch Amulet",
    "施法预备": "Spell Preparation",
    "思维破坏": "Mind Shatter",
    "思维侵入": "Mind Intrusion",
    "思维扰乱": "Mind Disruption",
    "暴风雪": "Blizzard",
    "火焰箭": "Fire Arrow",
    "连接绳": "Connecting Rope",
    "烈焰箭": "Blazing Arrow",
    "炎枪术": "Flame Lance",
    "冰风": "Ice Wind",
    "吹雪": "Flurry",
    "精神": "Mind",
    "锁具": "Locks",
})


def protect(text, argument_start=0):
    matches = []
    spans = []
    for regex, kind in ((FORMAT, "argument"), (NAMED, "argument"), (TAG, "literal")):
        for hit in regex.finditer(text):
            if not any(hit.start() < end and hit.end() > start for start, end, *_ in spans):
                spans.append((hit.start(), hit.end(), kind, hit.group()))
    spans.sort()
    if len(spans) > len(WORDS):
        raise ValueError(f"too many protected segments: {text[:80]}")
    output = []
    position = 0
    argument = argument_start
    for index, (start, end, kind, raw) in enumerate(spans):
        output.append(text[position:start])
        token = WORDS[index]
        output.append(token)
        replacement = "{p%d}" % argument if kind == "argument" else raw
        if kind == "argument":
            argument += 1
        matches.append((token, replacement))
        position = end
    output.append(text[position:])
    return "".join(output), matches


def apply_glossary(text, protected):
    for chinese, english in sorted(GLOSSARY.items(), key=lambda pair: len(pair[0]), reverse=True):
        while chinese in text:
            if len(protected) >= len(WORDS):
                raise ValueError(f"too many protected terms: {text[:80]}")
            token = WORDS[len(protected)]
            text = text.replace(chinese, " " + token + " ", 1)
            protected.append((token, " " + english + " "))
    return text, protected


def clean(text, protected):
    text = text.replace("▁", " ").strip()
    for token, value in sorted(protected, key=lambda pair: len(pair[0]), reverse=True):
        pattern = re.compile(re.escape(token), re.I)
        text, count = pattern.subn(lambda _: value, text)
        if count != 1:
            # The small model occasionally inserts a space inside a marker.
            suffix = token.removeprefix("Placeholder")
            fuzzy = re.compile(r"Place\s*hold(?:er)?\s*" + re.escape(suffix), re.I)
            text, count = fuzzy.subn(lambda _: value, text)
        if count != 1:
            raise ValueError(f"lost protected token {token}: {text}")
    punctuation = {"，": ", ", "。": ".", "；": "; ", "：": ": ", "、": ", ",
                   "（": "(", "）": ")", "“": '“', "”": '”', "「": '“', "」": '”',
                   "／": "/", "～": "–"}
    for source, target in punctuation.items():
        text = text.replace(source, target)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r" +([,.;:!?%)])", r"\1", text)
    text = re.sub(r"([“(]) +", r"\1", text)
    text = re.sub(r"(\{p\d+\}|\d+) stack Charge", r"\1 Charge", text)
    text = re.sub(r"\bThis Turn\b", "this turn", text)
    text = re.sub(r"\brounds\b", "turns", text, flags=re.I)
    text = re.sub(r"\bround\b", "turn", text, flags=re.I)
    text = re.sub(r"\bmagic powers?\b", "Mana", text, flags=re.I)
    text = re.sub(r"\bpleasure\b", "Arousal", text, flags=re.I)
    text = re.sub(r"\bsmart\b", "Dexterity", text, flags=re.I)
    return text.strip()


def translate_fragments(text, protected, processor, translator):
    """Rare safety path when the model drops a format marker."""
    tokens = [token for token, _ in protected]
    pieces = re.split("(" + "|".join(map(re.escape, tokens)) + ")", text)
    translatable = [piece for piece in pieces if piece and piece not in tokens]
    encoded = [processor.encode(piece, out_type=str) for piece in translatable]
    results = translator.translate_batch(encoded, beam_size=4, max_decoding_length=512) if encoded else []
    translated = iter(processor.decode(result.hypotheses[0]) for result in results)
    return "".join(piece if piece in tokens else (next(translated) if piece else "") for piece in pieces)


def translate_segments(text, processor, translator):
    pieces = [piece for piece in re.split(r"(?<=[。！？；\n])", text) if piece]
    split = []
    for piece in pieces:
        split.extend(part for part in re.split(r"(?<=，)", piece) if part)
    encoded = [processor.encode(piece, out_type=str) for piece in split]
    results = translator.translate_batch(encoded, beam_size=4, max_decoding_length=512)
    return "".join(processor.decode(result.hypotheses[0]) for result in results)


def translate_original_segments(original, processor, translator):
    parts = [part for part in re.split(r"(?<=[。！？；\n])", original) if part]
    prepared = []
    metadata = []
    argument = 0
    for part in parts:
        marked, protected = protect(part, argument)
        argument += sum(1 for _, value in protected if value.startswith("{p"))
        marked, protected = apply_glossary(marked, protected)
        prepared.append(marked)
        metadata.append(protected)
    encoded = [processor.encode(text, out_type=str) for text in prepared]
    results = translator.translate_batch(encoded, beam_size=4, max_decoding_length=512)
    output = []
    for marked, protected, result in zip(prepared, metadata, results):
        translated = processor.decode(result.hypotheses[0])
        try:
            output.append(clean(translated, protected))
        except ValueError:
            output.append(clean(translate_fragments(marked, protected, processor, translator), protected))
    return " ".join(output)


def main():
    inventory = json.loads((BUILD / "localization/inventory.json").read_text(encoding="utf-8"))
    sources = sorted({entry["text"] for entry in inventory["entries"]} | set(MANUAL), key=lambda text: (len(text), text))
    cache = json.loads(CACHE.read_text(encoding="utf-8")) if CACHE.exists() else {}
    pending = [text for text in sources if text not in cache and text not in MANUAL]
    processor = None
    translator = None
    if pending:
        if ctranslate2 is None or spm is None:
            raise SystemExit(
                "Missing offline translation dependencies in build/translation-lite; "
                f"{len(pending)} uncached source string(s) still require translation"
            )
        processor = spm.SentencePieceProcessor(model_file=str(MODEL / "sentencepiece.model"))
        translator = ctranslate2.Translator(str(MODEL / "model"), device="cpu")
    batch_size = 48
    for offset in range(0, len(pending), batch_size):
        originals = pending[offset:offset + batch_size]
        prepared = []
        metadata = []
        for original in originals:
            marked, protected = protect(original)
            marked, protected = apply_glossary(marked, protected)
            prepared.append(marked)
            metadata.append(protected)
        encoded = [processor.encode(text, out_type=str) for text in prepared]
        results = translator.translate_batch(encoded, beam_size=4, max_decoding_length=512)
        for original, prepared_text, protected, result in zip(originals, prepared, metadata, results):
            translated = processor.decode(result.hypotheses[0])
            try:
                cache[original] = clean(translated, protected)
            except ValueError:
                translated = translate_segments(prepared_text, processor, translator)
                try:
                    cache[original] = clean(translated, protected)
                except ValueError:
                    cache[original] = translate_original_segments(original, processor, translator)
            if CJK.search(cache[original]):
                raise ValueError(f"untranslated Chinese remains: {original} -> {cache[original]}")
        CACHE.write_text(json.dumps(cache, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"translated {min(offset + batch_size, len(pending))}/{len(pending)}", flush=True)
    messages = []
    for source in sources:
        digest = sha256(source.encode("utf-8")).hexdigest()[:24]
        text = MANUAL[source] if source in MANUAL else cache[source]
        messages.append({"id": "legacy.h" + digest, "source": source, "text": text})
    document = {"schema_version": 1, "locale": "en_US", "messages": messages}
    OUTPUT.write_text(json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(OUTPUT), "messages": len(messages)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
