$ErrorActionPreference = 'Stop'
# Freeze a common-Han Chinese collation table for identical offline PC/Android UI sorting.
# Rebuild explicitly when changing the collation source; runtime never calls host locale APIs.
$collation = [StringComparer]::Create([Globalization.CultureInfo]::GetCultureInfo('zh-CN'), $true)
$characters = [string[]](0x4E00..0x9FFF | ForEach-Object { [string][char]$_ })
[Array]::Sort($characters, $collation)
$orderedHan = $characters -join ''
$sourceLines = [Collections.Generic.List[string]]::new()
$sourceLines.Add('extends RefCounted')
$sourceLines.Add('# Generated by tools/generate-chinese-collation.ps1 using zh-CN collation.')
$sourceLines.Add('# Covers common Han U+4E00..U+9FFF; unknown characters keep natural Unicode order.')
$sourceLines.Add('const HAN=(')
for ($offset = 0; $offset -lt $orderedHan.Length; $offset += 256) {
    $count = [Math]::Min(256, $orderedHan.Length - $offset)
    $tail = if ($offset + $count -lt $orderedHan.Length) { '+' } else { ')' }
    $sourceLines.Add(' "' + $orderedHan.Substring($offset, $count) + '"' + $tail)
}
$sourceLines.Add('static var ranks: Dictionary={}')
$sourceLines.Add('')
$sourceLines.Add('static func key(value: String) -> String:')
$sourceLines.Add(' if ranks.is_empty():')
$sourceLines.Add('  for index in range(HAN.length()): ranks[HAN.unicode_at(index)]=index')
$sourceLines.Add(' var result=""')
$sourceLines.Add(' for character in value.to_lower():')
$sourceLines.Add('  var code=character.unicode_at(0)')
$sourceLines.Add('  result+=String.chr(0xF0000+int(ranks[code])) if ranks.has(code) else character')
$sourceLines.Add(' return result')
$destination = Join-Path (Split-Path -Parent $PSScriptRoot) 'ui/chinese_collation.gd'
[IO.File]::WriteAllText($destination, ($sourceLines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
