extends RefCounted
const Pointer=preload("res://tests/target_sidebar_ui_cases.gd")

static func run(t) -> void:
 var ui=t.ui
 var portrait=ui.find_child("EquipmentPortrait",true,false)
 var panel=ui.find_child("BodyEquipmentPanel",true,false)
 t.check(portrait.texture.get_image().detect_alpha()!=Image.ALPHA_NONE and portrait.stretch_mode==TextureRect.STRETCH_KEEP_ASPECT_CENTERED,"BODY transparent original portrait keeps aspect ratio")
 var slots=["eyes","mouth","neck","upper_arm","special_1","forearm","wrist","hands","special_2","special_3","thigh","calf","ankle","feet"]
 var previous=0.0
 for slot in slots:
  var rect=ui.body_buttons[slot].get_global_rect()
  t.check(rect.position.y>previous and panel.get_global_rect().encloses(rect) and rect.position.x>=portrait.get_global_rect().end.x,"BODY visible anatomical row fits beside portrait: "+slot)
  previous=rect.position.y
 t.check(ui.find_child("EquipmentDetails",true,false)==null,"BODY compact sidebar starts without large details overlay")
 await t.capture("ui-83-portrait-equipment-sidebar.png")
 var before=ui.game.export_snapshot()
 await t.inspect_body("toes")
 t.check(ui.game.export_snapshot()==before and t.visible_text(ui.find_child("EquipmentDetails",true,false)).contains("脚趾"),"BODY inspecting lowest free slot spends no resources or turn")
 await Pointer.press(t,ui.find_child("CloseEquipmentDetails",true,false))
 t.check(ui.find_child("EquipmentDetails",true,false)==null and ui.view.body_groups.size()==14,"BODY closing details preserves all body targets")
 await t.start_practice("Practice_head_harness")
 before=ui.game.export_snapshot()
 await t.inspect_body("eyes")
 t.check(ui.game.export_snapshot()==before and t.visible_text(ui.find_child("EquipmentDetails",true,false)).contains("眼罩"),"BODY head details show actual equipment without action")
 var cards=ui.find_child("EquipmentDetails",true,false).find_children("EquipmentCard_*","PanelContainer",true,false)
 t.check(cards.size()==2 and cards[0].get_parent() is GridContainer and cards[0].get_parent().columns==2,"BODY all masks share two-column small equipment cards")
 var first_rect=cards[0].get_global_rect()
 var second_rect=cards[1].get_global_rect()
 t.check(is_equal_approx(first_rect.position.y,second_rect.position.y) and first_rect.end.x<=second_rect.position.x,"BODY small cards sit beside each other without overlap")
 var toggle=cards[0].find_child("EquipmentCardDetailsToggle",true,false)
 await Pointer.press(t,toggle)
 t.check(toggle.text.contains("收起") and t.visible_text(cards[0]).contains("视觉受阻") and ui.game.export_snapshot()==before,"BODY expanding card reveals real details without state changes")
 await Pointer.press(t,toggle)
 t.check(toggle.text.contains("查看") and not t.visible_text(cards[0]).contains("视觉受阻") and ui.game.export_snapshot()==before,"BODY closing card details stays local and preserves gameplay")
 await t.capture("ui-84-body-equipment-details.png")
 var uid=ui.view.hand.filter(func(c):return c.type=="slip")[0].uid
 await t.start_drag(uid,"eyes")
 t.check(ui.find_child("EquipmentPortrait",true,false).is_visible_in_tree(),"BODY existing portrait stays visible while dragging to equipment")
 await t.capture("ui-85-body-card-drop.png")
 await t.mouse_button(Vector2(1100,90),MOUSE_BUTTON_LEFT,false)
 t.check(ui.game.export_snapshot()==before,"BODY cancelling drag out of target spends nothing")
 await t.start_practice("Practice_jacket")
 await t.inspect_body("hands")
 var detail=ui.find_child("EquipmentDetails",true,false)
 cards=detail.find_children("EquipmentCard_*","PanelContainer",true,false)
 t.check(cards.size()==1 and t.visible_text(cards[0]).contains("左手掌、右手掌"),"BODY shared jacket appears once with both palm locations")
 t.check(cards[0].size.x>300 and cards[0].get_parent().columns==1,"BODY single card uses available width instead of leaving an empty column")
 t.check(cards[0].find_child("EquipmentActions",true,false).visible,"BODY shared physical equipment opens actions once despite covering several subslots")
 await t.capture("ui-109-compact-jacket-card.png")
 ui.game=preload("res://tests/game_fixture.gd").new(42)
 ui.game.add_fixture("palm",4)
 ui.game.add_fixture("fingers",4)
 ui.render();await t.frames();await t.inspect_body("hands")
 detail=ui.find_child("EquipmentDetails",true,false)
 cards=detail.find_children("EquipmentCard_*","PanelContainer",true,false)
 t.check(cards.size()==2 and cards[0].get_parent()==cards[1].get_parent() and is_equal_approx(cards[0].position.y,cards[1].position.y),"BODY different hand subslots pack into the same row")
 t.check(t.visible_text(cards[0]).contains("手掌") and t.visible_text(cards[1]).contains("手指"),"BODY packed cards retain their exact subslot labels")
 await t.capture("ui-110-compact-cross-slot-cards.png")
 await shared_hand_target(t)
 await selection_focus(t)
 await single_click_play(t)

static func single_click_play(t) -> void:
 var ui=t.ui
 # A click on the hand card chooses the only physical restraint, even when
 # the previously inspected body slot is unrelated. Never infer a new action.
 for type in ["strain","concentration"]:
  ui.restart(42);ui.game.state.equipment.clear();ui.game._discard_end()
  ui.game.state.wall="normal"
  var target=ui.game.add_fixture("ankle",400,1000)
  var card=preload("res://tests/curse_cases.gd").give(ui.game,type)
  ui.selected_slot="wrist";ui.card_faces[card.uid]=type=="concentration"
  ui.render();await t.frames()
  var before=ui.game.export_snapshot()
  var c=ui.actions.find("card",{"uid":card.uid,"target":target.id,"free":ui.card_faces[card.uid]})
  await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid);await t.frames()
  t.check(c.valid and ui.game.state.version==before.version+1 and ui.game.state.energy==before.energy-c.cost,"SINGLE CLICK native hand click pays once using the current face: "+type)
  t.check(not ui.card_buttons.has(card.uid) and is_equal_approx(ui.game._equipment(target.id).durability,400-c.payload.preview.damage),"SINGLE CLICK removes the played card and applies exactly the formal preview: "+type)
  t.check(ui.selected_card=="" and ui.find_child("EquipmentDetails",true,false)==null and ui.find_child("PlaySelectedCard",true,false)==null,"SINGLE CLICK has no second target or play confirmation: "+type)
 ui.restart(42);ui.game.state.equipment.clear();ui.game._discard_end()
 var target=ui.game.add_fixture("ankle",400,1000)
 var card=preload("res://tests/curse_cases.gd").give(ui.game,"strain")
 ui.game.state.energy=0;ui.selected_slot="eyes";ui.render();await t.frames()
 var before=ui.game.export_snapshot()
 var blocked=ui.actions.find("card",{"uid":card.uid,"target":target.id,"free":false})
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid);await t.frames()
 t.check(ui.game.state==before and ui.card_buttons.has(card.uid),"SINGLE CLICK insufficient energy preserves card, resources and random state")
 t.check(not blocked.valid and t.visible_text(ui.find_child("EquipmentDetails",true,false)).contains(blocked.reason),"SINGLE CLICK blocked unique target shows its actual reason at the correct body slot")
 await t.close_information()
 ui.game.state.energy=3;ui.game.add_fixture("wrist",4,10);ui.render();await t.frames()
 before=ui.game.export_snapshot()
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid);await t.frames()
 t.check(ui.game.state==before and ui.selected_card==card.uid,"SINGLE CLICK multiple physical restraints continue to require target selection")
 await t.close_information()
 ui.game.state.equipment=ui.game.state.equipment.filter(func(e):return e.id==target.id)
 ui.render();await t.frames()
 ui.game.state.version+=1
 before=ui.game.export_snapshot()
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid);await t.frames()
 t.check(ui.game.state==before and ui.card_buttons.has(card.uid) and ui.notice.contains("状态已更新"),"SINGLE CLICK stale view cannot spend a card through automatic targeting")
 await t.start_practice("Practice_guard")
 ui.game.state.equipment.clear();ui.game.state.links.clear();ui.game.state.composites.clear()
 ui.game._discard_end();ui.game.add_fixture("wrist",4,10)
 ui.game.CaptureBind.apply_bind(ui.game,ui.game.state.enemies[0])
 card=preload("res://tests/curse_cases.gd").give(ui.game,"strain")
 ui.render();await t.frames();before=ui.game.export_snapshot()
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid);await t.frames()
 t.check(not ui.view.guard_bind.is_empty() and ui.game.state==before and ui.selected_card==card.uid,"SINGLE CLICK capture bar plus one restraint preserves explicit choice")

static func selection_focus(t) -> void:
 var ui=t.ui
 ui.restart(42);ui.game.state.equipment.clear();ui.game._discard_end()
 ui.game.state.wall="normal";ui.game.state.wall_distance=0
 var ankle=ui.game.add_fixture("ankle",4,10)
 ui.game.add_fixture("wrist",4,10)
 var card=preload("res://tests/curse_cases.gd").give(ui.game,"crossed_legs")
 ui.render();await t.frames()
 var before=ui.game.export_snapshot()
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid)
 t.check(ui.selected_card==card.uid and ui.game.export_snapshot()==before,"FOCUS native card selection does not execute an action")
 t.check(ui.body_buttons.ankle.get_meta("target_selectable",false) and not ui.body_buttons.wrist.get_meta("target_selectable",true),"FOCUS leg-only card highlights a usable leg and dims occupied but ineligible wrists")
 t.check(ui.body_buttons.ankle.modulate.r>ui.body_buttons.wrist.modulate.r,"FOCUS valid and invalid body targets differ visibly")
 await Pointer.press(t,ui.body_buttons.ankle)
 var candidate=ui.actions.find("card",{"uid":card.uid,"target":ankle.id,"free":false})
 t.check(candidate.valid and ui.selected_candidate==candidate.id and ui.find_child("PlaySelectedCard",true,false)!=null and ui.find_child("CardTarget_"+ankle.id,true,false)==null,"FOCUS single restraint skips selection and exposes the formal play action")
 t.check(ui.game.export_snapshot()==before,"FOCUS opening single target preserves resources, card and random state")
 await t.capture("ui-card-target-focus.png")
 var hand_id=ui.card_buttons[card.uid].get_instance_id()
 await t.flip(card.uid)
 for body in ui.view.body_groups:
  var available=preload("res://ui/drag_targets.gd").choices(ui,{"card_uid":card.uid,"free":true,"version":ui.view.version})
  var usable=available.any(func(c):return c.payload.get("slot","") in body.slots or body.targets.has(c.payload.get("target","")))
  t.check(ui.body_buttons[body.id].get_meta("target_selectable")==usable,"FOCUS face flip refreshes formal availability: "+body.id)
 t.check(ui.card_buttons[card.uid].get_instance_id()==hand_id and ui.game.export_snapshot()==before,"FOCUS face flip retains the hand control and gameplay state")
 await t.flip(card.uid)
 ui.game.state.energy=0;ui.render();await t.frames()
 t.check(not ui.body_buttons.ankle.get_meta("target_selectable",true) and ui.find_child("PlaySelectedCard",true,false)==null,"FOCUS insufficient energy dims the otherwise valid target and prevents play")
 candidate=ui.actions.find("card",{"uid":card.uid,"target":ankle.id,"free":false})
 t.check(t.visible_text(ui.find_child("EquipmentDetails",true,false)).contains(candidate.reason),"FOCUS auto-selected blocked equipment keeps its exact unavailable reason")
 await Pointer.press(t,ui.find_child("CloseEquipmentDetails",true,false))
 t.check(not ui.body_buttons.ankle.has_meta("target_selectable") and ui.body_buttons.ankle.modulate==Color.WHITE,"FOCUS cancel restores ordinary body appearance")
 ui.game.state.energy=3
 ui.game.add_fixture("ankle",4,10)
 ui.render();await t.frames()
 before=ui.game.export_snapshot()
 await preload("res://tests/curse_ui_cases.gd").click_card(t,card.uid)
 t.check(ui.selected_candidate=="" and ui.find_child("PlaySelectedCard",true,false)==null,"FOCUS multiple physical restraints retain target selection")
 var buttons=ui.find_child("EquipmentDetails",true,false).find_children("CardTarget_*","Button",true,false)
 t.check(buttons.size()==2,"FOCUS multiple restraints each have a selectable or dimmed entry")
 for button in buttons:
  t.check(button.get_meta("target_selectable")==not button.disabled,"FOCUS item brightness follows the actual candidate")
 var valid=ui._body_card_actions("ankle",card.uid).filter(func(c):return c.payload.free==false and c.valid)[0]
 await Pointer.press(t,ui.find_child("CardTarget_"+valid.payload.target,true,false))
 t.check(ui.selected_candidate==valid.id and ui.game.export_snapshot()==before,"FOCUS selecting one of several targets spends nothing")
 await Pointer.press(t,ui.find_child("PlaySelectedCard",true,false))
 t.check(ui.view.energy==before.energy-valid.cost and not ui.card_buttons.has(card.uid),"FOCUS play submits exactly the selected formal candidate once")

static func shared_hand_target(t) -> void:
 var ui=t.ui
 ui.game=preload("res://tests/game_fixture.gd").new(42)
 var tape=ui.game._install_template("tape","fingers",12.8,16,false,"fixture",2)
 var root=ui.game._install_assembly("glove","long","fixture",2,2)
 var body=ui.game._composite_body(root)
 var wrist=ui.game._install_template("belt","wrist",4,10,false,"fixture")
 ui.render();await t.frames()
 var uid=ui.view.hand.filter(func(c):return c.type=="slip")[0].uid
 if ui.card_faces.get(uid,false): await t.flip(uid)
 var before=ui.game.export_snapshot()
 var choices=ui._body_card_actions("hands",uid)
 var shell=choices.filter(func(c):return c.payload.target==body.id)[0]
 var inner=choices.filter(func(c):return c.payload.target==tape.id)[0]
 await t.start_drag(uid,"hands")
 t.check(choices.size()==2 and ui.drop_targets.size()==2 and ui.drop_targets.has(shell.id) and ui.drop_targets.has(inner.id),"BODY aimed hand shows its two physical pieces including blocked entries, without other regions")
 t.check(ui.drop_targets.values().all(func(button):return not button.get_meta("target_selectable") and button.get_parent().modulate.r<0.5),"BODY blocked hand pieces are visible at low brightness")
 await t.release_target(await t.reveal_drop_target(inner.id))
 t.check(ui.game.export_snapshot()==before and ui.drop_targets.is_empty(),"BODY releasing over dimmed equipment rejects the action without payment or state changes")
 await preload("res://tests/curse_ui_cases.gd").click_card(t,uid)
 await t.inspect_body("hands")
 var details=ui.find_child("EquipmentDetails",true,false)
 t.check(shell.reason.contains("肩带") and not shell.reason.contains("最外层") and t.visible_text(details).contains(shell.reason),"BODY glove entry names the shoulder restriction instead of labeling every hand target inner")
 t.check(inner.reason.contains(body.name) and inner.reason.contains("覆盖") and t.visible_text(details).contains(inner.reason),"BODY inner tape entry identifies the glove covering it")
 var blocked=ui.find_child("CardTarget_"+tape.id,true,false)
 t.check(blocked.disabled and not blocked.get_meta("target_selectable",true),"BODY blocked inner equipment remains visible and dimmed")
 await Pointer.press(t,blocked)
 t.check(ui.game.export_snapshot()==before,"BODY rejected inner-tape click does not spend energy, consume card or change RNG")
 await Pointer.press(t,ui.find_child("CloseEquipmentDetails",true,false))
 # Clear actual blockers through the existing damage/cleanup path, then use
 # the same deduplicated candidate in a real card drop.
 ui.game._apply_equipment_damage(root.components.filter(func(e):return e.part=="left")[0],100,"cut")
 ui.game._apply_equipment_damage(wrist,100,"cut");ui.game._cleanup()
 ui.render();await t.frames()
 choices=ui._body_card_actions("hands",uid)
 shell=choices.filter(func(c):return c.payload.target==body.id)[0]
 t.check(shell.valid and not choices.filter(func(c):return c.payload.target==tape.id)[0].valid,"BODY removing shoulder and wrist cover enables only the outer glove")
 var durability=body.durability;var damage=shell.payload.preview.damage;var energy=ui.view.energy
 await t.start_drag(uid,"hands")
 t.check(ui.drop_targets[shell.id].get_meta("target_selectable") and ui.drop_targets[shell.id].get_parent().modulate==Color.WHITE and not ui.drop_targets[inner.id].get_meta("target_selectable") and ui.drop_targets[inner.id].get_parent().modulate.r<0.5,"BODY same region distinguishes selectable outer piece from dimmed blocked inner piece")
 await t.capture("ui-body-target-brightness.png")
 await t.release_target(await t.reveal_drop_target(shell.id))
 t.check(is_equal_approx(ui.game._equipment(body.id).get("durability",0),maxf(0,durability-damage)) and ui.view.energy==energy-shell.cost,"BODY deduplicated glove target still commits the original candidate once")
