extends RefCounted
const Navigation=preload("res://tests/interface_ui_cases.gd")
const Settings=preload("res://ui/display_settings.gd")

static func choose(t, name: String, index: int) -> void:
 var picker=t.ui.find_child(name,true,false)
 t.check(picker!=null and not picker.disabled,"DISPLAY enabled selector "+name)
 if picker==null or picker.disabled: return
 picker.select(index);picker.item_selected.emit(index)
 await t.frames(10)

static func portrait_refresh(t) -> void:
 var ui=t.ui
 ui.restart(20260906);await t.frames(8)
 var before=ui.game.export_snapshot()
 var hero=ui.find_child("HeroArt",true,false)
 var equipment=ui.find_child("EquipmentPortrait",true,false)
 var enemy=ui.find_child("EnemyArt_*",true,false)
 var layout_id=ui.layout.get_instance_id()
 var sprite=hero.hero_sprite
 var draws=[0,0,0]
 hero.draw.connect(func():draws[0]+=1)
 equipment.draw.connect(func():draws[1]+=1)
 enemy.draw.connect(func():draws[2]+=1)
 await t.frames(8)
 draws.assign([0,0,0])
 for count in range(3):
  ui.render(ui.view)
  await t.frames(3)
 t.check(ui.layout.get_instance_id()==layout_id,"DISPLAY scene root persists across ordinary view refreshes")
 t.check(ui.find_child("HeroArt",true,false)==hero and hero.hero_sprite==sprite,"DISPLAY unchanged hero keeps its arena and sprite instances")
 t.check(ui.find_child("EquipmentPortrait",true,false)==equipment and ui.find_child("EnemyArt_*",true,false)==enemy,"DISPLAY equipment and enemy portrait instances survive UI refreshes")
 t.check(draws==[0,0,0],"DISPLAY unrelated UI refreshes do not redraw portraits")
 t.check(not hero.is_processing() and not enemy.is_processing(),"DISPLAY portraits have no idle frame callbacks")
 t.check(ui.game.export_snapshot()==before,"DISPLAY retained scenes never mutate game state")
 # The procedural fallback must also stay idle (not just texture-backed enemies).
 var fallback=preload("res://ui/elements/arena.tscn").instantiate()
 fallback.mode="six_bind";fallback.size=Vector2(240,288)
 ui.add_child(fallback)
 var fallback_draws=[0]
 fallback.draw.connect(func():fallback_draws[0]+=1)
 await t.frames(8);fallback_draws[0]=0
 await t.frames(12)
 t.check(fallback_draws[0]==0 and not fallback.is_processing(),"DISPLAY procedural enemy portrait does not redraw every frame")
 ui.remove_child(fallback);fallback.queue_free()
 var changed=ui.view.duplicate(true)
 changed.posture="sit"
 hero.configure_hero(changed,false);await t.frames(3)
 t.check(hero.pose=="sit" and hero.hero_sprite.texture==preload("res://ui/pixel_art.gd").hero_texture("sit",ui.view.has_restraint_level),"DISPLAY posture changes update the existing hero scene")
 hero.configure_hero(ui.view,false);await t.frames(3)
 t.check(hero.pose==ui.view.posture,"DISPLAY restoring the pose restores the retained portrait")
 hero.configure_hero(ui.view,true);equipment.configure(ui.view,true);await t.frames(4)
 draws.assign([0,0,0])
 hero.configure_hero(changed,true);equipment.configure(changed,true);await t.frames(4)
 t.check(draws[0]==0 and draws[1]==0,"DISPLAY fixed portraits ignore posture changes that cannot alter their image")
 hero.configure_hero(ui.view,false);equipment.configure(ui.view,false);await t.frames(4)
 draws.assign([0,0,0])
 ui.display_settings.art_changed.emit("cards",enemy.template)
 ui.display_settings.art_changed.emit("enemies","unrelated_enemy")
 await t.frames(3)
 t.check(draws[2]==0,"DISPLAY unrelated art imports do not invalidate this enemy")
 var enemy_node=enemy.get_instance_id()
 ui.display_settings.art_changed.emit("enemies",enemy.template)
 await t.frames(3)
 t.check(enemy.get_instance_id()==enemy_node and draws[2]>0,"DISPLAY matching art imports refresh the existing enemy scene")

static func run(t) -> void:
 var ui=t.ui
 await portrait_refresh(t)
 var backdrop=ui.find_child("MoonlitGallery",true,false)
 var static_draws=[0]
 backdrop.draw.connect(func():static_draws[0]+=1)
 await t.frames(8)
 static_draws[0]=0
 await t.frames(12)
 t.check(static_draws[0]==0,"DISPLAY idle decorative animation does not redraw static scenery")
 t.check(Engine.max_fps==60,"DISPLAY game presentation defaults to a 60 FPS budget")
 var old_mode=t.root.mode;var old_border=t.root.borderless;var old_size=t.root.size;var old_position=t.root.position
 var before=ui.game.export_snapshot()
 await t.open_menu();await Navigation.press(t,"OpenOptions")
 var fps=ui.find_child("FrameLimit",true,false)
 t.check(fps.item_count==4 and range(4).map(func(index):return fps.get_item_text(index))==["60帧","120帧","240帧","无上限"],"DISPLAY exposes all four frame budgets")
 for index in range(4):
  await choose(t,"FrameLimit",index)
  t.check(Engine.max_fps==[60,120,240,0][index] and ui.display_settings.frame_limit==Engine.max_fps,"DISPLAY frame selection immediately changes the actual engine budget")
 await Navigation.press(t,"VSyncEnabled")
 t.check(not ui.display_settings.vsync_enabled and DisplayServer.window_get_vsync_mode(t.root.get_window_id())==DisplayServer.VSYNC_DISABLED,"DISPLAY vertical sync can be disabled independently of the unlimited budget")
 await choose(t,"FrameLimit",1)
 await Navigation.press(t,"VSyncEnabled")
 t.check(ui.display_settings.vsync_enabled and Engine.max_fps==120 and DisplayServer.window_get_vsync_mode(t.root.get_window_id())==DisplayServer.VSYNC_ENABLED,"DISPLAY vertical sync re-enables without replacing the chosen frame cap")
 var picker=ui.find_child("DisplayMode",true,false)
 t.check(picker.item_count==3 and range(3).map(func(index):return picker.get_item_text(index))==["窗口","无边框窗口","全屏"],"DISPLAY three distinct native window modes")
 var sizes=ui.display_settings.choices()
 t.check(Vector2i(3840,2160) in sizes and Vector2i(2560,1440) in sizes,"DISPLAY 1440p and 4K stay selectable regardless of monitor size")
 var small=sizes.find(Vector2i(1280,720))
 t.check(small>=0,"DISPLAY 720p is selectable on test monitor")
 await choose(t,"DisplayResolution",small)
 t.check(t.root.size==Vector2i(1280,720) and t.root.mode==Window.MODE_WINDOWED and not t.root.borderless,"DISPLAY resolution changes actual framed window")
 await choose(t,"DisplayMode",1)
 t.check(t.root.mode==Window.MODE_WINDOWED and t.root.borderless and t.root.size==Vector2i(1280,720),"DISPLAY borderless retains chosen window resolution")
 await choose(t,"DisplayMode",2)
 t.check(t.root.mode==Window.MODE_FULLSCREEN and ui.find_child("DisplayResolution",true,false).disabled,"DISPLAY fullscreen uses monitor size and does not offer ineffective window resolution")
 await choose(t,"DisplayMode",0)
 t.check(t.root.mode==Window.MODE_WINDOWED and not t.root.borderless and t.root.size==Vector2i(1280,720),"DISPLAY leaving fullscreen restores chosen size and clears forced borderless flag")
 t.check(Engine.max_fps==120 and ui.display_settings.vsync_enabled,"DISPLAY window transitions retain frame and sync preferences")
 t.check(ui.game.export_snapshot()==before,"DISPLAY changing resolution and modes never changes game or turn state")
 await t.capture("ui-display-settings.png")
 # The same preference reader/writer uses a test-only file, never the player's settings.
 var path="res://build/display-settings-%s.cfg" % OS.get_process_id()
 var settings=Settings.new();settings.path=path;settings.initialize(t.root,false)
 settings.persistence_enabled=true;settings.set_mode(1)
 settings.set_frame_limit(240);settings.set_vsync(false)
 settings.set_art_style("enemies","six_bind","test")
 settings.set_art_style("cards","strain","test")
 settings.set_art_style("cards","slip","test")
 settings.set_chastity_locks(true);settings.adjust_chastity_chance(10)
 t.check(not settings.cursed_plate_start and not settings.cursed_plate_masochist_mode,"CUSTOM DISPLAY cursed-plate preferences default off")
 settings.set_cursed_plate_start(true)
 settings.set_cursed_plate_masochist_mode(true)
 var custom_reload=Settings.new();custom_reload.path=path;custom_reload.initialize(t.root)
 t.check(custom_reload.frame_limit==240 and not custom_reload.vsync_enabled and Engine.max_fps==240 and DisplayServer.window_get_vsync_mode(t.root.get_window_id())==DisplayServer.VSYNC_DISABLED,"DISPLAY frame and sync preferences persist and apply in a fresh settings instance")
 settings.set_frame_limit(0)
 custom_reload.initialize(t.root)
 t.check(custom_reload.frame_limit==0 and Engine.max_fps==0,"DISPLAY unlimited survives preference reload")
 t.check(not settings.set_frame_limit(90) and settings.frame_limit==0 and Engine.max_fps==0,"DISPLAY unsupported frame cap is rejected without side effects")
 t.check(custom_reload.cursed_plate_start and custom_reload.cursed_plate_masochist_mode and custom_reload.chastity_locks_enabled,"CUSTOM DISPLAY enabled cursed-plate preferences persist")
 t.check(settings.chastity_locks_enabled and settings.chastity_lock_chance==35,"DISPLAY chastity pool defaults to 25 percent and adjusts in five-point steps")
 settings.set_fixed_hero_portrait(true)
 t.check(not settings.cursed_plate_start and not settings.cursed_plate_masochist_mode,"CUSTOM DISPLAY fixed portrait clears both cursed-plate preferences")
 t.check(not settings.chastity_locks_enabled,"DISPLAY fixed hero portrait disables the incompatible chastity pool")
 settings.set_resolution(Vector2i(3840,2160))
 t.check(settings.resolution==Vector2i(3840,2160),"DISPLAY selecting 4K keeps requested resolution")
 t.check(settings.save_error.is_empty() and FileAccess.file_exists(path),"DISPLAY preferences saved separately from game snapshots")
 var restored=Settings.new();restored.path=path;restored.initialize(t.root)
 t.check(restored.mode==1 and restored.resolution==Vector2i(3840,2160) and t.root.borderless,"DISPLAY fresh settings instance restores persisted mode and size")
 t.check(restored.fixed_hero_portrait,"DISPLAY fixed portrait preference survives a settings reload")
 t.check(not restored.chastity_locks_enabled and restored.chastity_lock_chance==35,"DISPLAY fixed portrait keeps the saved chance but suppresses the chastity pool")
 t.check(restored.art_style("enemies","six_bind")=="test" and restored.art_choices.cards.keys().size()==2,"ART each card and enemy choice persists independently alongside display settings")
 restored.set_art_style("enemies","six_bind","formal")
 t.check(restored.art_texture("enemies","six_bind")!=null and restored.art_choices.cards==settings.art_choices.cards,"ART changing one enemy keeps both card preferences")
 var config=ConfigFile.new();config.set_value("display","mode",99);config.set_value("display","resolution",Vector2i(99999,99999));config.set_value("gameplay","chastity_locks_enabled","invalid");config.set_value("gameplay","chastity_lock_chance",27);config.save(path)
 restored.initialize(t.root)
 t.check(restored.frame_limit==60 and restored.vsync_enabled and Engine.max_fps==60,"DISPLAY absent pacing settings use safe defaults")
 config.set_value("display","frame_limit",90);config.set_value("display","vsync_enabled","invalid");config.save(path)
 restored.initialize(t.root)
 t.check(restored.frame_limit==60 and restored.vsync_enabled and DisplayServer.window_get_vsync_mode(t.root.get_window_id())==DisplayServer.VSYNC_ENABLED,"DISPLAY malformed pacing settings fall back to 60 FPS and vertical sync")
 t.check(not restored.fixed_hero_portrait,"DISPLAY missing fixed portrait setting defaults off")
 t.check(not restored.chastity_locks_enabled and restored.chastity_lock_chance==25,"DISPLAY invalid chastity settings fall back to off and 25 percent")
 restored.set_cursed_plate_start(true)
 restored.set_cursed_plate_masochist_mode(true)
 t.check(not restored.cursed_plate_start and not restored.cursed_plate_masochist_mode,"CUSTOM DISPLAY disabled pool cannot set cursed-plate preferences")
 config.set_value("gameplay","cursed_plate_start",true);config.save(path);restored.initialize(t.root)
 t.check(not restored.cursed_plate_start,"CUSTOM DISPLAY inconsistent saved setting is suppressed")
 config.set_value("gameplay","chastity_locks_enabled",true);config.set_value("gameplay","cursed_plate_start","invalid");config.save(path);restored.initialize(t.root)
 t.check(not restored.cursed_plate_start,"CUSTOM DISPLAY malformed saved setting defaults off")
 config.set_value("gameplay","chastity_lock_chance",0);config.save(path)
 restored.initialize(t.root)
 t.check(restored.chastity_lock_chance==5,"DISPLAY formerly saved zero chance clamps to five percent")
 restored.set_chastity_locks(true);restored.adjust_chastity_chance(-5)
 t.check(restored.chastity_lock_chance==5,"DISPLAY repeated lowering cannot pass the five-percent minimum")
 restored.adjust_chastity_chance(200)
 t.check(restored.chastity_lock_chance==100,"DISPLAY probability upper bound stays at one hundred percent")
 t.check(restored.mode in range(3) and restored.resolution in restored.choices(),"DISPLAY invalid saved preference falls back to supported resolution")
 DirAccess.remove_absolute(path)
 t.root.mode=Window.MODE_WINDOWED;t.root.borderless=old_border;t.root.size=old_size;t.root.position=old_position;t.root.mode=old_mode
 ui.display_settings.initialize(t.root,false)
 await t.close_information();await t.frames()
 await preload("res://tests/card_music_ui_cases.gd").run(t)
