extends RefCounted
const Store=preload("res://core/save_store.gd")
const Click=preload("res://tests/interface_ui_cases.gd")

const Home=preload("res://tests/home_ui_cases.gd")

static func art_choices(t) -> void:
 var ui=t.ui;var settings=ui.display_settings
 var before=ui.game.export_snapshot();var choices=settings.art_choices.duplicate(true)
 var persist=settings.persistence_enabled;settings.persistence_enabled=false
 settings.art_choices.clear()
 await Click.press(t,"EncyclopediaCategory_enemies")
 var book=ui.find_child("Encyclopedia",true,false)
 book.show_entry(book.rows.filter(func(row):return row.category=="enemies" and row.id=="six_bind")[0]);await t.frames()
 var picker=ui.find_child("EncyclopediaArtStyle",true,false)
 var picture=ui.find_child("EncyclopediaEnemyImage",true,false)
 t.check(picker.selected==1 and picture.enemy_sprite.texture.resource_path.ends_with("enemy-six-bind-formal-v1.png"),"ART six binds defaults to supplied formal art in encyclopedia")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(not is_instance_valid(picture.enemy_sprite) and book.selected=="six_bind","ART individual selector restores procedural test artwork and retains book focus")
 picker.select(1);picker.item_selected.emit(1);await t.frames()
 t.check(is_instance_valid(picture.enemy_sprite),"ART switching back recreates formal preview immediately")
 await Click.press(t,"EncyclopediaCategory_cards")
 picker=ui.find_child("EncyclopediaArtStyle",true,false)
 var face=ui.find_child("DisplayCard_encyclopedia_"+book.selected,true,false)
 t.check(picker.is_item_disabled(1) and ui.find_child("EncyclopediaArtNote",true,false).text=="正式版立绘未添加" and face.get_node("CardIllustration").texture==face.ILLUSTRATIONS[face.symbol],"ART missing formal card keeps original illustration with explicit unavailable option")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(settings.art_style("enemies","six_bind")=="formal" and ui.game.export_snapshot()==before,"ART card preference neither changes enemy preference nor gameplay state")
 book.show_entry(book.rows.filter(func(row):return row.category=="cards" and row.id=="crossed_legs")[0]);await t.frames()
 picker=ui.find_child("EncyclopediaArtStyle",true,false)
 face=ui.find_child("DisplayCard_encyclopedia_crossed_legs",true,false)
 var art=face.get_node("CardIllustration");var official=art.texture
 t.check(picker.selected==1 and not picker.is_item_disabled(1) and official.resource_path.ends_with("card-crossed-legs-formal-v1.png") and official.get_image().detect_alpha()!=Image.ALPHA_NONE,"ART crossed legs defaults to supplied transparent formal portrait over unchanged card backdrop")
 face.flip_requested.emit();await t.frames()
 t.check(art.texture==official and art.stretch_mode==TextureRect.STRETCH_KEEP_ASPECT_CENTERED and art.material==null,"ART both card faces keep the same full portrait without stretching or color key")
 picker.select(0);picker.item_selected.emit(0);await t.frames()
 t.check(art.texture==face.ILLUSTRATIONS.crossed_legs,"ART crossed legs test drawing remains selectable")
 picker.select(1);picker.item_selected.emit(1);await t.frames()
 t.check(art.texture==official and ui.game.export_snapshot()==before,"ART switching formal portrait changes no card rules or game state")
 await t.capture("ui-crossed-legs-formal.png")
 settings.art_choices=choices;settings.persistence_enabled=persist

static func run(t) -> void:
 var store=Store.new("res://build/home-ui-"+str(Time.get_ticks_usec()))
 await Home.boot(t,store)
 var ui=t.ui
 var initial=ui.game.export_snapshot()
 await Click.press(t,"HomeEncyclopedia")
 t.check(ui.show_home and ui.show_encyclopedia and ui.find_child("Encyclopedia",true,false)!=null,"BOOK opens above home")
 var equipment_picture=ui.find_child("EncyclopediaEquipmentImage",true,false)
 var first_entry=ui.find_child("EncyclopediaEntries",true,false).get_child(0)
 t.check(equipment_picture!=null and first_entry.icon==equipment_picture.texture and equipment_picture.stretch_mode==TextureRect.STRETCH_KEEP_ASPECT_CENTERED and equipment_picture.get_parent().get_global_rect().encloses(equipment_picture.get_global_rect()),"BOOK list thumbnail and bounded detail image share the equipment art")
 await t.capture("ui-equipment-book-images.png")
 await Click.press(t,"EncyclopediaCategory_items")
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==ui.game.Tools.TYPES.size() and not ui.find_child("EncyclopediaGrade",true,false).visible,"BOOK item category lists all definitions without irrelevant grade controls")
 var item_group=ui.find_child("EncyclopediaGroup",true,false)
 var item_branches=range(1,item_group.item_count).map(func(index):return item_group.get_item_metadata(index))
 t.check(item_branches==["药剂","卷轴","工具"],"BOOK separate potion, scroll and tool filters")
 item_group.select(2);item_group.item_selected.emit(2);await t.frames()
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==ui.game.Tools.TYPES.values().filter(func(spec):return spec.get("category","")=="scroll").size(),"BOOK scroll filter matches actual registry")
 item_group.select(0);item_group.item_selected.emit(0);await t.frames()
 var item_search=ui.find_child("EncyclopediaSearch",true,false)
 item_search.text="锯条";item_search.text_changed.emit(item_search.text);await t.frames()
 await Click.press(t,"EncyclopediaEntry_saw")
 var item_detail=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==1 and item_detail.contains("7点真实伤害") and item_detail.contains("使用次数：2") and item_detail.contains("安装后") and ui.find_child("EncyclopediaItemIcon",true,false).symbol=="saw","BOOK searchable tool detail shows damage, uses and shared installation effect")
 t.check(ui.game.export_snapshot()==initial and not store.has_files("tower"),"BOOK item browsing neither starts a run nor changes gameplay")
 await t.capture("ui-encyclopedia-items.png")
 item_search.text="";item_search.text_changed.emit("");await t.frames()
 await Click.press(t,"EncyclopediaCategory_special")
 var image_search=ui.find_child("EncyclopediaSearch",true,false)
 image_search.text=ui.game.SpecialEquipment.TYPES.urethral_rod_medium.name;image_search.text_changed.emit(image_search.text);await t.frames()
 await Click.press(t,"EncyclopediaEntry_urethral_rod_medium")
 equipment_picture=ui.find_child("EncyclopediaEquipmentImage",true,false)
 t.check(equipment_picture!=null and equipment_picture.texture.resource_path.ends_with("focus-c-silicone-urethral-rod.png"),"BOOK selecting illustrated special equipment shows the existing local picture")
 image_search.text="";image_search.text_changed.emit("");await t.frames()
 await Click.press(t,"EncyclopediaEntry_nipple_clamp_low")
 t.check(ui.find_child("EncyclopediaEquipmentImage",true,false)==null and ui.game.export_snapshot()==initial,"BOOK missing-image selection clears previous picture without changing gameplay")
 for category in ["equipment","special","enemies","cards"]:
  await Click.press(t,"EncyclopediaCategory_"+category)
  t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()>0,"BOOK populated category "+category)
 await art_choices(t)
 var hidden_variants=["magic_hand_gift","hannya_swallow","hannya_infusion","hannya_henshin","hannya_2","hannya_3","hannya_4","good_soup"]
 t.check(hidden_variants.all(func(id):return ui.find_child("EncyclopediaEntry_"+id,true,false)==null),"BOOK UI omits duplicate special card variants")
 var variant_search=ui.find_child("EncyclopediaSearch",true,false)
 for title in ["身轻如燕","灌注","魔术手","henshin"]:
  variant_search.text=title;variant_search.text_changed.emit(title);await t.frames()
  var matches=ui.find_child("EncyclopediaEntries",true,false).get_children()
  t.check(matches.filter(func(button):return button.text.begins_with(title+" ·")).size()==1 and hidden_variants.all(func(id):return ui.find_child("EncyclopediaEntry_"+id,true,false)==null),"BOOK UI search has one original-name row without variant duplicates: "+title)
 variant_search.text="品相完美";variant_search.text_changed.emit(variant_search.text);await t.frames()
 t.check(ui.find_child("EncyclopediaEntry_henshin",true,false)!=null and hidden_variants.all(func(id):return ui.find_child("EncyclopediaEntry_"+id,true,false)==null),"BOOK UI special name search finds its original without a duplicate row")
 variant_search.text="";variant_search.text_changed.emit("");await t.frames()
 var family_book=ui.find_child("Encyclopedia",true,false)
 for term in ["般若汤","般若汤-其二","般若汤-其三","般若汤-其四","好汤喝够"]:
  variant_search.text=term;variant_search.text_changed.emit(term);await t.frames()
  var soup_rows=ui.find_child("EncyclopediaEntries",true,false).get_children()
  t.check(soup_rows.size()==1 and soup_rows[0].name=="EncyclopediaEntry_hannya_1" and ui.find_child("DisplayCard_encyclopedia_good_soup",true,false)!=null,"BOOK soup and descendant searches lead only to complete first-stage family: "+term)
 variant_search.text="";variant_search.text_changed.emit("");await t.frames()
 for original in family_book.Catalog.CARD_VARIANTS:
  family_book.show_entry(family_book.rows.filter(func(row):return row.category=="cards" and row.id==original)[0]);await t.frames()
  var original_face=ui.find_child("DisplayCard_encyclopedia_"+original,true,false)
  var child_id=family_book.Catalog.CARD_VARIANTS[original][0]
  var child_face=ui.find_child("DisplayCard_encyclopedia_"+child_id,true,false)
  t.check(original_face!=null and child_face!=null and child_face.drag_payload.is_empty(),"BOOK original and special variant share the detail page: "+original)
  var old_side=original_face.free_face;var child_side=child_face.free_face
  child_face.flip_requested.emit();await t.frames()
  t.check(child_face.free_face!=child_side and original_face.free_face==old_side and ui.game.export_snapshot()==initial,"BOOK variant flips independently without changing original or game: "+original)
 family_book.show_entry(family_book.rows.filter(func(row):return row.category=="cards" and row.id=="hannya_1")[0]);await t.frames()
 var flow=ui.find_child("EncyclopediaCardFamily",true,false)
 for stage in range(1,4):
  var soup_face=ui.find_child("DisplayCard_encyclopedia_hannya_%d" % stage,true,false)
  var next_name=family_book.Catalog.B.CARD_NAMES["hannya_%d" % (stage+1)]
  t.check(t.visible_text(soup_face).contains(next_name+"加入弃牌堆"),"BOOK visible soup card spells out generated card name: "+next_name)
 t.check(flow.get_child_count()==8 and family_book.Catalog.related_cards("hannya_1").all(func(id):return ui.find_child("DisplayCard_encyclopedia_"+id,true,false)!=null),"BOOK soup page includes every downstream card in one scrollable family")
 t.check(flow.get_children().all(func(section):return section.position.x>=0 and section.position.x+section.size.x<=flow.size.x+1),"BOOK card family wraps inside available detail width")
 var family_scroll=ui.find_child("EncyclopediaDetail",true,false).get_parent()
 family_scroll.scroll_vertical=10000;await t.frames()
 t.check(ui.find_child("DisplayCard_encyclopedia_good_soup",true,false).get_global_rect().intersects(family_scroll.get_global_rect()),"BOOK final descendant remains reachable by scrolling")
 var branch=ui.find_child("EncyclopediaGroup",true,false)
 var branches=range(1,branch.item_count).map(func(index):return branch.get_item_metadata(index))
 t.check(ui.game.Cards.Rules.TYPES.values().all(func(label):return label+"牌" in branches) and branches.all(func(label):return branches.count(label)==1),"BOOK includes registered card branches and distinct combined-type branches")
 branch.select(4);branch.item_selected.emit(4);await t.frames()
 t.check(t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains("慌乱"),"BOOK dedicated curse branch")
 var face=ui.find_child("DisplayCard_encyclopedia_panic",true,false)
 t.check(face!=null and face.drag_payload.is_empty() and not face.lift_on_hover and face.size==Vector2(226,290),"BOOK uses hand card face without gameplay drag")
 face.flip_requested.emit();await t.frames()
 t.check(not face.free_face and ui.game.export_snapshot()==initial and not store.has_files("tower"),"BOOK single-face curse cannot flip or start a run")
 var search=ui.find_child("EncyclopediaSearch",true,false)
 search.text="无匹配图鉴";search.text_changed.emit(search.text);await t.frames()
 t.check(t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains("暂无条目"),"BOOK search empty result")
 search.text="";search.text_changed.emit("");await t.frames()
 await t.capture("ui-encyclopedia-curse.png")
 branch.select(5);branch.item_selected.emit(5);await t.frames()
 var status_face=ui.find_child("DisplayCard_encyclopedia_tease",true,false)
 t.check(ui.find_child("EncyclopediaEntries",true,false).get_child_count()==ui.game.Cards.Rules.SPECS.values().filter(func(spec):return spec.card_type=="status").size() and status_face!=null and status_face.rarity=="status" and t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains("状态"),"BOOK status branch renders all registered status cards using the shared card face")
 branch.select(3);branch.item_selected.emit(3)
 var rarity=ui.find_child("EncyclopediaGrade",true,false)
 rarity.select(4);rarity.item_selected.emit(4);await t.frames()
 var ability_rows=ui.find_child("EncyclopediaEntries",true,false).get_children()
 var ability_detail=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 t.check(not ability_rows.is_empty() and ability_detail.contains("能力牌") and ability_detail.contains("稀有") and rarity.visible,"BOOK combines ability branch and rare filter without assuming first card ordering")
 await Click.press(t,"EncyclopediaCategory_relics");await t.frames()
 var axe_book=ui.find_child("Encyclopedia",true,false)
 axe_book.show_entry(axe_book.rows.filter(func(row):return row.category=="relics" and row.id=="cursed_plate_lock")[0]);await t.frames()
 var cursed_text=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 var cursed_icon=ui.find_child("EncyclopediaRelicIcon",true,false)
 t.check(cursed_text.contains("无限持续") and cursed_text.contains("自动解锁并取下整件") and cursed_icon!=null and cursed_icon.glyph.texture==cursed_icon.ART.cursed_plate_lock,"CURSED PLATE encyclopedia shows dedicated artwork and automatic key removal rule")
 axe_book.show_entry(axe_book.rows.filter(func(row):return row.category=="relics" and row.id=="axe_amulet")[0]);await t.frames()
 var axe_text=t.visible_text(ui.find_child("EncyclopediaDetail",true,false))
 var axe_icon=ui.find_child("EncyclopediaRelicIcon",true,false)
 t.check(axe_text.contains("斧护符") and axe_text.contains("罕见") and axe_text.contains("进入精英房、Boss房或监狱时，恢复20魔力") and axe_icon!=null and axe_icon.ART.has("axe_amulet"),"AXE encyclopedia shows uncommon name, entry effect and registered icon")
 rarity=ui.find_child("EncyclopediaGrade",true,false)
 t.check(range(1,rarity.item_count).map(func(i):return rarity.get_item_metadata(i))==ui.game.Relics.RARITIES.keys() and rarity.visible,"RELIC encyclopedia exposes registered rarity filters including special collectibles")
 rarity.select(3);rarity.item_selected.emit(3);await t.frames()
 var relic_rows=ui.find_child("EncyclopediaEntries",true,false).get_children()
 t.check(relic_rows.all(func(row):return row.icon!=null),"RELIC encyclopedia list reuses actual relic artwork")
 var relic_icon=ui.find_child("EncyclopediaRelicIcon",true,false)
 t.check(relic_icon!=null and relic_icon.glyph is TextureRect and relic_icon.glyph.texture==preload("res://ui/relic_icon.gd").ART[relic_icon.relic.id] and relic_icon.badge==null,"RELIC encyclopedia detail shows shared artwork without inventing a live counter")
 await t.capture("ui-encyclopedia-relics.png")
 t.check(relic_rows.size()==ui.game.Relics.TYPES.values().filter(func(r):return r.rarity=="rare").size() and ui.game.Relics.TYPES.values().any(func(r):return r.rarity=="rare" and t.visible_text(ui.find_child("EncyclopediaDetail",true,false)).contains(r.name)),"RELIC rare filter selects actual registered rare relics")
 t.check(ui.game.export_snapshot()==initial and not store.has_files("tower"),"RELIC browsing and filtering never change the run or create a save")
 await t.close_information()
 t.check(ui.show_home and not ui.show_encyclopedia,"BOOK closes back to homepage")
 ui.persistence_enabled=false;ui.feedback_duration=0.04
